/* AUTO-GENERATED ASLp LIFTER FILE */
package aslloader
import util.Logger
import ir._

def f_aarch64_vector_arithmetic_binary_element_mul_acc_fp16_sisd (v_st: LiftState,v_enc: BV) : Unit = {
  if (f_eq_bits(v_st, BigInt(1), bvextract(v_st,v_enc,BigInt(11),BigInt(1)), mkBits(v_st, 1, BigInt("1", 2)))) then {
    assert (((f_sle_bits(v_st, BigInt(6), mkBits(v_st, 6, BigInt("000000", 2)), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(5),BigInt(5)), BigInt(6)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(5),BigInt(5)), BigInt(6)), mkBits(v_st, 6, BigInt("011111", 2))))))
    assert (((f_sle_bits(v_st, BigInt(5), mkBits(v_st, 5, BigInt("00000", 2)), f_ZeroExtend(v_st, BigInt(4), BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(4)), BigInt(5)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(4), BigInt(6), bvextract(v_st,v_enc,BigInt(16),BigInt(4)), BigInt(6)), mkBits(v_st, 6, BigInt("011111", 2))))))
    assert (((f_sle_bits(v_st, BigInt(6), mkBits(v_st, 6, BigInt("000000", 2)), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)), mkBits(v_st, 6, BigInt("011111", 2))))))
    val v_result__1 = Mutable[Expr](rTExprDefault)
    assert (((f_sle_bits(v_st, BigInt(4), mkBits(v_st, 4, BigInt("0000", 2)), f_ZeroExtend(v_st, BigInt(3), BigInt(4), f_append_bits(v_st, BigInt(2), BigInt(1), f_append_bits(v_st, BigInt(1), BigInt(1), bvextract(v_st,v_enc,BigInt(11),BigInt(1)), bvextract(v_st,v_enc,BigInt(21),BigInt(1))), bvextract(v_st,v_enc,BigInt(20),BigInt(1))), BigInt(4)))) && (f_sle_bits(v_st, BigInt(9), f_ZeroExtend(v_st, BigInt(8), BigInt(9), f_add_bits(v_st, BigInt(8), f_ZeroExtend(v_st, BigInt(7), BigInt(8), f_mul_bits(v_st, BigInt(7), f_ZeroExtend(v_st, BigInt(3), BigInt(7), f_append_bits(v_st, BigInt(2), BigInt(1), f_append_bits(v_st, BigInt(1), BigInt(1), bvextract(v_st,v_enc,BigInt(11),BigInt(1)), bvextract(v_st,v_enc,BigInt(21),BigInt(1))), bvextract(v_st,v_enc,BigInt(20),BigInt(1))), BigInt(7)), mkBits(v_st, 7, BigInt("0010000", 2))), BigInt(8)), mkBits(v_st, 8, BigInt("00010000", 2))), BigInt(9)), mkBits(v_st, 9, BigInt("010000000", 2))))))
    if (f_eq_bits(v_st, BigInt(1), bvextract(v_st,v_enc,BigInt(14),BigInt(1)), mkBits(v_st, 1, BigInt("1", 2)))) then {
      val v_Exp22__2 = Mutable[Expr](rTExprDefault)
      v_Exp22__2.v = f_gen_FPMulAdd(v_st, BigInt(16), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(0),BigInt(5)))), BigInt(0), BigInt(16)), f_gen_append_bits(v_st, BigInt(1), BigInt(15), f_gen_not_bits(v_st, BigInt(1), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(15), BigInt(1))), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(0), BigInt(15))), f_gen_slice(v_st, f_gen_slice(v_st, f_gen_lsr_bits(v_st, BigInt(128), BigInt(8), f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(4), bvextract(v_st,v_enc,BigInt(16),BigInt(4)))), f_gen_bit_lit(v_st, BigInt(8), f_ZeroExtend(v_st, BigInt(7), BigInt(8), f_mul_bits(v_st, BigInt(7), f_ZeroExtend(v_st, BigInt(3), BigInt(7), f_append_bits(v_st, BigInt(2), BigInt(1), f_append_bits(v_st, BigInt(1), BigInt(1), bvextract(v_st,v_enc,BigInt(11),BigInt(1)), bvextract(v_st,v_enc,BigInt(21),BigInt(1))), bvextract(v_st,v_enc,BigInt(20),BigInt(1))), BigInt(7)), mkBits(v_st, 7, BigInt("0010000", 2))), BigInt(8)))), BigInt(0), BigInt(16)), BigInt(0), BigInt(16)), f_gen_load(v_st, v_FPCR.v))
      v_result__1.v = v_Exp22__2.v
    } else {
      val v_Exp27__2 = Mutable[Expr](rTExprDefault)
      v_Exp27__2.v = f_gen_FPMulAdd(v_st, BigInt(16), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(0),BigInt(5)))), BigInt(0), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(0), BigInt(16)), f_gen_slice(v_st, f_gen_slice(v_st, f_gen_lsr_bits(v_st, BigInt(128), BigInt(8), f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(4), bvextract(v_st,v_enc,BigInt(16),BigInt(4)))), f_gen_bit_lit(v_st, BigInt(8), f_ZeroExtend(v_st, BigInt(7), BigInt(8), f_mul_bits(v_st, BigInt(7), f_ZeroExtend(v_st, BigInt(3), BigInt(7), f_append_bits(v_st, BigInt(2), BigInt(1), f_append_bits(v_st, BigInt(1), BigInt(1), bvextract(v_st,v_enc,BigInt(11),BigInt(1)), bvextract(v_st,v_enc,BigInt(21),BigInt(1))), bvextract(v_st,v_enc,BigInt(20),BigInt(1))), BigInt(7)), mkBits(v_st, 7, BigInt("0010000", 2))), BigInt(8)))), BigInt(0), BigInt(16)), BigInt(0), BigInt(16)), f_gen_load(v_st, v_FPCR.v))
      v_result__1.v = v_Exp27__2.v
    }
    assert (((f_sle_bits(v_st, BigInt(6), mkBits(v_st, 6, BigInt("000000", 2)), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)), mkBits(v_st, 6, BigInt("011111", 2))))))
    f_gen_array_store (v_st,v__Z.v,f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(0),BigInt(5))),f_gen_ZeroExtend(v_st, BigInt(16), BigInt(128), v_result__1.v, f_gen_int_lit(v_st, BigInt(128))))
  } else {
    assert (((f_sle_bits(v_st, BigInt(6), mkBits(v_st, 6, BigInt("000000", 2)), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(5),BigInt(5)), BigInt(6)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(5),BigInt(5)), BigInt(6)), mkBits(v_st, 6, BigInt("011111", 2))))))
    assert (((f_sle_bits(v_st, BigInt(5), mkBits(v_st, 5, BigInt("00000", 2)), f_ZeroExtend(v_st, BigInt(4), BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(4)), BigInt(5)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(4), BigInt(6), bvextract(v_st,v_enc,BigInt(16),BigInt(4)), BigInt(6)), mkBits(v_st, 6, BigInt("011111", 2))))))
    assert (((f_sle_bits(v_st, BigInt(6), mkBits(v_st, 6, BigInt("000000", 2)), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)), mkBits(v_st, 6, BigInt("011111", 2))))))
    val v_result__1 = Mutable[Expr](rTExprDefault)
    assert (((f_sle_bits(v_st, BigInt(4), mkBits(v_st, 4, BigInt("0000", 2)), f_ZeroExtend(v_st, BigInt(3), BigInt(4), f_append_bits(v_st, BigInt(2), BigInt(1), f_append_bits(v_st, BigInt(1), BigInt(1), bvextract(v_st,v_enc,BigInt(11),BigInt(1)), bvextract(v_st,v_enc,BigInt(21),BigInt(1))), bvextract(v_st,v_enc,BigInt(20),BigInt(1))), BigInt(4)))) && (f_sle_bits(v_st, BigInt(9), f_ZeroExtend(v_st, BigInt(8), BigInt(9), f_add_bits(v_st, BigInt(8), f_ZeroExtend(v_st, BigInt(7), BigInt(8), f_mul_bits(v_st, BigInt(7), f_ZeroExtend(v_st, BigInt(3), BigInt(7), f_append_bits(v_st, BigInt(2), BigInt(1), f_append_bits(v_st, BigInt(1), BigInt(1), bvextract(v_st,v_enc,BigInt(11),BigInt(1)), bvextract(v_st,v_enc,BigInt(21),BigInt(1))), bvextract(v_st,v_enc,BigInt(20),BigInt(1))), BigInt(7)), mkBits(v_st, 7, BigInt("0010000", 2))), BigInt(8)), mkBits(v_st, 8, BigInt("00010000", 2))), BigInt(9)), mkBits(v_st, 9, BigInt("001000000", 2))))))
    if (f_eq_bits(v_st, BigInt(1), bvextract(v_st,v_enc,BigInt(14),BigInt(1)), mkBits(v_st, 1, BigInt("1", 2)))) then {
      val v_Exp55__2 = Mutable[Expr](rTExprDefault)
      v_Exp55__2.v = f_gen_FPMulAdd(v_st, BigInt(16), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(0),BigInt(5)))), BigInt(0), BigInt(16)), f_gen_append_bits(v_st, BigInt(1), BigInt(15), f_gen_not_bits(v_st, BigInt(1), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(15), BigInt(1))), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(0), BigInt(15))), f_gen_slice(v_st, f_gen_slice(v_st, f_gen_lsr_bits(v_st, BigInt(64), BigInt(8), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(4), bvextract(v_st,v_enc,BigInt(16),BigInt(4)))), BigInt(0), BigInt(64)), f_gen_bit_lit(v_st, BigInt(8), f_ZeroExtend(v_st, BigInt(7), BigInt(8), f_mul_bits(v_st, BigInt(7), f_ZeroExtend(v_st, BigInt(3), BigInt(7), f_append_bits(v_st, BigInt(2), BigInt(1), f_append_bits(v_st, BigInt(1), BigInt(1), bvextract(v_st,v_enc,BigInt(11),BigInt(1)), bvextract(v_st,v_enc,BigInt(21),BigInt(1))), bvextract(v_st,v_enc,BigInt(20),BigInt(1))), BigInt(7)), mkBits(v_st, 7, BigInt("0010000", 2))), BigInt(8)))), BigInt(0), BigInt(16)), BigInt(0), BigInt(16)), f_gen_load(v_st, v_FPCR.v))
      v_result__1.v = v_Exp55__2.v
    } else {
      val v_Exp60__2 = Mutable[Expr](rTExprDefault)
      v_Exp60__2.v = f_gen_FPMulAdd(v_st, BigInt(16), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(0),BigInt(5)))), BigInt(0), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(0), BigInt(16)), f_gen_slice(v_st, f_gen_slice(v_st, f_gen_lsr_bits(v_st, BigInt(64), BigInt(8), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(4), bvextract(v_st,v_enc,BigInt(16),BigInt(4)))), BigInt(0), BigInt(64)), f_gen_bit_lit(v_st, BigInt(8), f_ZeroExtend(v_st, BigInt(7), BigInt(8), f_mul_bits(v_st, BigInt(7), f_ZeroExtend(v_st, BigInt(3), BigInt(7), f_append_bits(v_st, BigInt(2), BigInt(1), f_append_bits(v_st, BigInt(1), BigInt(1), bvextract(v_st,v_enc,BigInt(11),BigInt(1)), bvextract(v_st,v_enc,BigInt(21),BigInt(1))), bvextract(v_st,v_enc,BigInt(20),BigInt(1))), BigInt(7)), mkBits(v_st, 7, BigInt("0010000", 2))), BigInt(8)))), BigInt(0), BigInt(16)), BigInt(0), BigInt(16)), f_gen_load(v_st, v_FPCR.v))
      v_result__1.v = v_Exp60__2.v
    }
    assert (((f_sle_bits(v_st, BigInt(6), mkBits(v_st, 6, BigInt("000000", 2)), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)), mkBits(v_st, 6, BigInt("011111", 2))))))
    f_gen_array_store (v_st,v__Z.v,f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(0),BigInt(5))),f_gen_ZeroExtend(v_st, BigInt(16), BigInt(128), v_result__1.v, f_gen_int_lit(v_st, BigInt(128))))
  }
}
