/* AUTO-GENERATED ASLp LIFTER FILE */
package aslloader
import util.Logger
import ir._

def f_aarch64_vector_bfmmla (v_st: LiftState,v_enc: BitVecLiteral) : Unit = {
  assert (((f_sle_bits(v_st, BigInt(6), BitVecLiteral(BigInt("000000", 2), 6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(5),BigInt(5)), BigInt(6)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(5),BigInt(5)), BigInt(6)), BitVecLiteral(BigInt("011111", 2), 6)))))
  assert (((f_sle_bits(v_st, BigInt(6), BitVecLiteral(BigInt("000000", 2), 6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(16),BigInt(5)), BigInt(6)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(16),BigInt(5)), BigInt(6)), BitVecLiteral(BigInt("011111", 2), 6)))))
  assert (((f_sle_bits(v_st, BigInt(6), BitVecLiteral(BigInt("000000", 2), 6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)), BitVecLiteral(BigInt("011111", 2), 6)))))
  val v_Exp19__3 : RTSym = f_decl_bv(v_st, "Exp19__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp19__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(0), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(0), BigInt(16))))
  val v_Exp22__3 : RTSym = f_decl_bv(v_st, "Exp22__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp22__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(16), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(16), BigInt(16))))
  val v_Exp23__3 : RTSym = f_decl_bv(v_st, "Exp23__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp23__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp19__3), f_gen_load(v_st, v_Exp22__3)))
  val v_Exp24__3 : RTSym = f_decl_bv(v_st, "Exp24__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp24__3,f_gen_BFAdd(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(0),BigInt(5)))), BigInt(0), BigInt(32)), f_gen_load(v_st, v_Exp23__3)))
  val v_Exp27__3 : RTSym = f_decl_bv(v_st, "Exp27__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp27__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(32), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(32), BigInt(16))))
  val v_Exp30__3 : RTSym = f_decl_bv(v_st, "Exp30__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp30__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(48), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(48), BigInt(16))))
  val v_Exp31__3 : RTSym = f_decl_bv(v_st, "Exp31__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp31__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp27__3), f_gen_load(v_st, v_Exp30__3)))
  val v_Exp32__3 : RTSym = f_decl_bv(v_st, "Exp32__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp32__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp24__3), f_gen_load(v_st, v_Exp31__3)))
  val v_Exp38__3 : RTSym = f_decl_bv(v_st, "Exp38__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp38__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(0), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(64), BigInt(16))))
  val v_Exp41__3 : RTSym = f_decl_bv(v_st, "Exp41__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp41__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(16), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(80), BigInt(16))))
  val v_Exp42__3 : RTSym = f_decl_bv(v_st, "Exp42__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp42__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp38__3), f_gen_load(v_st, v_Exp41__3)))
  val v_Exp43__3 : RTSym = f_decl_bv(v_st, "Exp43__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp43__3,f_gen_BFAdd(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(0),BigInt(5)))), BigInt(32), BigInt(32)), f_gen_load(v_st, v_Exp42__3)))
  val v_Exp46__3 : RTSym = f_decl_bv(v_st, "Exp46__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp46__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(32), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(96), BigInt(16))))
  val v_Exp49__3 : RTSym = f_decl_bv(v_st, "Exp49__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp49__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(48), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(112), BigInt(16))))
  val v_Exp50__3 : RTSym = f_decl_bv(v_st, "Exp50__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp50__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp46__3), f_gen_load(v_st, v_Exp49__3)))
  val v_Exp51__3 : RTSym = f_decl_bv(v_st, "Exp51__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp51__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp43__3), f_gen_load(v_st, v_Exp50__3)))
  val v_Exp56__3 : RTSym = f_decl_bv(v_st, "Exp56__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp56__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(64), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(0), BigInt(16))))
  val v_Exp59__3 : RTSym = f_decl_bv(v_st, "Exp59__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp59__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(80), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(16), BigInt(16))))
  val v_Exp60__3 : RTSym = f_decl_bv(v_st, "Exp60__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp60__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp56__3), f_gen_load(v_st, v_Exp59__3)))
  val v_Exp61__3 : RTSym = f_decl_bv(v_st, "Exp61__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp61__3,f_gen_BFAdd(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(0),BigInt(5)))), BigInt(64), BigInt(32)), f_gen_load(v_st, v_Exp60__3)))
  val v_Exp64__3 : RTSym = f_decl_bv(v_st, "Exp64__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp64__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(96), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(32), BigInt(16))))
  val v_Exp67__3 : RTSym = f_decl_bv(v_st, "Exp67__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp67__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(112), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(48), BigInt(16))))
  val v_Exp68__3 : RTSym = f_decl_bv(v_st, "Exp68__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp68__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp64__3), f_gen_load(v_st, v_Exp67__3)))
  val v_Exp69__3 : RTSym = f_decl_bv(v_st, "Exp69__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp69__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp61__3), f_gen_load(v_st, v_Exp68__3)))
  val v_Exp74__3 : RTSym = f_decl_bv(v_st, "Exp74__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp74__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(64), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(64), BigInt(16))))
  val v_Exp77__3 : RTSym = f_decl_bv(v_st, "Exp77__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp77__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(80), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(80), BigInt(16))))
  val v_Exp78__3 : RTSym = f_decl_bv(v_st, "Exp78__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp78__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp74__3), f_gen_load(v_st, v_Exp77__3)))
  val v_Exp79__3 : RTSym = f_decl_bv(v_st, "Exp79__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp79__3,f_gen_BFAdd(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(0),BigInt(5)))), BigInt(96), BigInt(32)), f_gen_load(v_st, v_Exp78__3)))
  val v_Exp82__3 : RTSym = f_decl_bv(v_st, "Exp82__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp82__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(96), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(96), BigInt(16))))
  val v_Exp85__3 : RTSym = f_decl_bv(v_st, "Exp85__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp85__3,f_gen_BFMul(v_st, f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(5),BigInt(5)))), BigInt(112), BigInt(16)), f_gen_slice(v_st, f_gen_array_load(v_st, v__Z.v, f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(16),BigInt(5)))), BigInt(112), BigInt(16))))
  val v_Exp86__3 : RTSym = f_decl_bv(v_st, "Exp86__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp86__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp82__3), f_gen_load(v_st, v_Exp85__3)))
  val v_Exp87__3 : RTSym = f_decl_bv(v_st, "Exp87__3", BigInt(32)) 
  f_gen_store (v_st,v_Exp87__3,f_gen_BFAdd(v_st, f_gen_load(v_st, v_Exp79__3), f_gen_load(v_st, v_Exp86__3)))
  assert (((f_sle_bits(v_st, BigInt(6), BitVecLiteral(BigInt("000000", 2), 6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)))) && (f_sle_bits(v_st, BigInt(6), f_ZeroExtend(v_st, BigInt(5), BigInt(6), bvextract(v_st,v_enc,BigInt(0),BigInt(5)), BigInt(6)), BitVecLiteral(BigInt("011111", 2), 6)))))
  f_gen_array_store (v_st,v__Z.v,f_cvt_bits_uint(v_st, BigInt(5), bvextract(v_st,v_enc,BigInt(0),BigInt(5))),f_gen_append_bits(v_st, BigInt(32), BigInt(96), f_gen_load(v_st, v_Exp87__3), f_gen_append_bits(v_st, BigInt(32), BigInt(64), f_gen_load(v_st, v_Exp69__3), f_gen_append_bits(v_st, BigInt(32), BigInt(32), f_gen_load(v_st, v_Exp51__3), f_gen_load(v_st, v_Exp32__3)))))
}
