// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir;

public class PrettyPrinter
{
  //For certain applications increasing the initial size of the buffer may improve performance.
  private static final int INITIAL_BUFFER_SIZE = 128;
  private static final int INDENT_WIDTH = 2;
  //You may wish to change the parentheses used in precedence.
  private static final String _L_PAREN = new String("(");
  private static final String _R_PAREN = new String(")");
  //You may wish to change render
  private static void render(String s)
  {
    if (s.equals("{"))
    {
       onEmptyLine();
       buf_.append(s);
       _n_ = _n_ + INDENT_WIDTH;
       buf_.append("\n");
       indent();
    }
    else if (s.equals("(") || s.equals("["))
       buf_.append(s);
    else if (s.equals(")") || s.equals("]"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals("}"))
    {
       _n_ = _n_ - INDENT_WIDTH;
       onEmptyLine();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals(","))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append(" ");
    }
    else if (s.equals(";"))
    {
       removeTrailingWhitespace();
       buf_.append(s);
       buf_.append("\n");
       indent();
    }
    else if (s.equals("")) return;
    else if (s.trim().equals(""))
    {
       backup();
       buf_.append(s);
    }
    else
    {
       buf_.append(s);
       buf_.append(" ");
    }
  }


  //  print and show methods are defined for each category.
  public static String print(basil_ir.Absyn.Program foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.Program foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.ListDeclaration foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.ListDeclaration foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.ListBIdent foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.ListBIdent foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.Declaration foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.Declaration foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.MExpr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.MExpr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.IntType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.IntType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.BoolType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.BoolType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.MapType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.MapType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.BVType foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.BVType foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.Type foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.Type foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.ListExpr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.ListExpr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.IntVal foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.IntVal foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.AddrAttr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.AddrAttr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.Endian foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.Endian foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.ListStatement foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.ListStatement foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.Statement foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.Statement foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.CallLVars foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.CallLVars foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.Jump foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.Jump foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.LVar foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.LVar foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.ListLVar foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.ListLVar foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.ListBlock foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.ListBlock foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.Block foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.Block foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.PEntry foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.PEntry foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.PAddress foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.PAddress foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.InternalBlocks foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.InternalBlocks foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.ProcDef foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.ProcDef foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.Params foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.Params foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.ListParams foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.ListParams foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.Expr foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.Expr foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.BinOp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.BinOp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.UnOp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.UnOp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.BVUnOp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.BVUnOp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.BVBinOp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.BVBinOp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.BVLogicalBinOp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.BVLogicalBinOp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.IntBinOp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.IntBinOp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.IntLogicalBinOp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.IntLogicalBinOp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String print(basil_ir.Absyn.BoolBinOp foo)
  {
    pp(foo, 0);
    trim();
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  public static String show(basil_ir.Absyn.BoolBinOp foo)
  {
    sh(foo);
    String temp = buf_.toString();
    buf_.delete(0,buf_.length());
    return temp;
  }
  /***   You shouldn't need to change anything beyond this point.   ***/

  private static void pp(basil_ir.Absyn.Program foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.Prog)
    {
       basil_ir.Absyn.Prog _prog = (basil_ir.Absyn.Prog) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_prog.listdeclaration_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.ListDeclaration foo, int _i_)
  {
    ppListDeclaration(foo.iterator(), _i_);
  }

  private static void ppListDeclaration(java.util.Iterator<basil_ir.Absyn.Declaration> it, int _i_)
  {
    if (it.hasNext())
    {
      basil_ir.Absyn.Declaration el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(";"); ppListDeclaration(it, _i_);
      }
    }
  }


  private static void pp(basil_ir.Absyn.ListBIdent foo, int _i_)
  {
    ppListBIdent(foo.iterator(), _i_);
  }

  private static void ppListBIdent(java.util.Iterator<String> it, int _i_)
  {
    if (it.hasNext())
    {
      String el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListBIdent(it, _i_);
      }
    }
  }


  private static void pp(basil_ir.Absyn.Declaration foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.LetDecl)
    {
       basil_ir.Absyn.LetDecl _letdecl = (basil_ir.Absyn.LetDecl) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("let");
       pp(_letdecl.bident_, 0);
       render("=");
       pp(_letdecl.mexpr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.MemDecl)
    {
       basil_ir.Absyn.MemDecl _memdecl = (basil_ir.Absyn.MemDecl) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("memory");
       pp(_memdecl.bident_, 0);
       render(":");
       pp(_memdecl.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.VarDecl)
    {
       basil_ir.Absyn.VarDecl _vardecl = (basil_ir.Absyn.VarDecl) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("var");
       pp(_vardecl.bident_, 0);
       render(":");
       pp(_vardecl.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.Procedure)
    {
       basil_ir.Absyn.Procedure _procedure = (basil_ir.Absyn.Procedure) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("proc");
       pp(_procedure.bident_, 0);
       render("(");
       pp(_procedure.listparams_1, 0);
       render(")");
       render("->");
       render("(");
       pp(_procedure.listparams_2, 0);
       render(")");
       pp(_procedure.procdef_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.MExpr foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.MSym)
    {
       basil_ir.Absyn.MSym _msym = (basil_ir.Absyn.MSym) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_msym.bident_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BlockM)
    {
       basil_ir.Absyn.BlockM _blockm = (basil_ir.Absyn.BlockM) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_blockm.block_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.IntType foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.IntT)
    {
       basil_ir.Absyn.IntT _intt = (basil_ir.Absyn.IntT) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("int");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.BoolType foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.BoolT)
    {
       basil_ir.Absyn.BoolT _boolt = (basil_ir.Absyn.BoolT) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bool");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.MapType foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.MapT)
    {
       basil_ir.Absyn.MapT _mapt = (basil_ir.Absyn.MapT) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("map");
       pp(_mapt.type_1, 0);
       pp(_mapt.beginlist_, 0);
       pp(_mapt.type_2, 0);
       pp(_mapt.endlist_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.BVType foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.BVT)
    {
       basil_ir.Absyn.BVT _bvt = (basil_ir.Absyn.BVT) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_bvt.bvtype_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.Type foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.TypeIntType)
    {
       basil_ir.Absyn.TypeIntType _typeinttype = (basil_ir.Absyn.TypeIntType) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_typeinttype.inttype_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.TypeBoolType)
    {
       basil_ir.Absyn.TypeBoolType _typebooltype = (basil_ir.Absyn.TypeBoolType) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_typebooltype.booltype_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.TypeMapType)
    {
       basil_ir.Absyn.TypeMapType _typemaptype = (basil_ir.Absyn.TypeMapType) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_typemaptype.maptype_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.TypeBVType)
    {
       basil_ir.Absyn.TypeBVType _typebvtype = (basil_ir.Absyn.TypeBVType) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_typebvtype.bvtype_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.ListExpr foo, int _i_)
  {
    ppListExpr(foo.iterator(), _i_);
  }

  private static void ppListExpr(java.util.Iterator<basil_ir.Absyn.Expr> it, int _i_)
  {
    if (it.hasNext())
    {
      basil_ir.Absyn.Expr el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListExpr(it, _i_);
      }
    }
  }


  private static void pp(basil_ir.Absyn.IntVal foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.HexInt)
    {
       basil_ir.Absyn.HexInt _hexint = (basil_ir.Absyn.HexInt) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_hexint.integerhex_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.DecInt)
    {
       basil_ir.Absyn.DecInt _decint = (basil_ir.Absyn.DecInt) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_decint.integer_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.AddrAttr foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.AddrAttrSome)
    {
       basil_ir.Absyn.AddrAttrSome _addrattrsome = (basil_ir.Absyn.AddrAttrSome) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_addrattrsome.beginrec_, 0);
       render("address");
       render("=");
       pp(_addrattrsome.intval_, 0);
       pp(_addrattrsome.endrec_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.AddrAttrNone)
    {
       basil_ir.Absyn.AddrAttrNone _addrattrnone = (basil_ir.Absyn.AddrAttrNone) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.AddrAttrEmpty)
    {
       basil_ir.Absyn.AddrAttrEmpty _addrattrempty = (basil_ir.Absyn.AddrAttrEmpty) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_addrattrempty.beginrec_, 0);
       pp(_addrattrempty.endrec_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.Endian foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.LittleEndian)
    {
       basil_ir.Absyn.LittleEndian _littleendian = (basil_ir.Absyn.LittleEndian) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("le");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BigEndian)
    {
       basil_ir.Absyn.BigEndian _bigendian = (basil_ir.Absyn.BigEndian) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("be");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.ListStatement foo, int _i_)
  {
    ppListStatement(foo.iterator(), _i_);
  }

  private static void ppListStatement(java.util.Iterator<basil_ir.Absyn.Statement> it, int _i_)
  {
    if (it.hasNext())
    { /* cons */
      basil_ir.Absyn.Statement el = it.next();
      pp(el, _i_); render(";"); ppListStatement(it, _i_);
    }
  }


  private static void pp(basil_ir.Absyn.Statement foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.Assign)
    {
       basil_ir.Absyn.Assign _assign = (basil_ir.Absyn.Assign) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_assign.lvar_, 0);
       render(":=");
       pp(_assign.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.SLoad)
    {
       basil_ir.Absyn.SLoad _sload = (basil_ir.Absyn.SLoad) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_sload.lvar_, 0);
       render(":=");
       render("load");
       pp(_sload.endian_, 0);
       pp(_sload.bident_, 0);
       pp(_sload.expr_, 0);
       pp(_sload.intval_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.SStore)
    {
       basil_ir.Absyn.SStore _sstore = (basil_ir.Absyn.SStore) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("store");
       pp(_sstore.endian_, 0);
       pp(_sstore.bident_, 0);
       pp(_sstore.expr_1, 0);
       pp(_sstore.expr_2, 0);
       pp(_sstore.intval_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.DirectCall)
    {
       basil_ir.Absyn.DirectCall _directcall = (basil_ir.Absyn.DirectCall) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_directcall.calllvars_, 0);
       render("call");
       pp(_directcall.bident_, 0);
       render("(");
       pp(_directcall.listexpr_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.IndirectCall)
    {
       basil_ir.Absyn.IndirectCall _indirectcall = (basil_ir.Absyn.IndirectCall) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("indirect");
       render("call");
       pp(_indirectcall.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.Assume)
    {
       basil_ir.Absyn.Assume _assume = (basil_ir.Absyn.Assume) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("assume");
       pp(_assume.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.Assert)
    {
       basil_ir.Absyn.Assert _assert = (basil_ir.Absyn.Assert) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("assert");
       pp(_assert.expr_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.CallLVars foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.NoOutParams)
    {
       basil_ir.Absyn.NoOutParams _nooutparams = (basil_ir.Absyn.NoOutParams) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.LocalVars)
    {
       basil_ir.Absyn.LocalVars _localvars = (basil_ir.Absyn.LocalVars) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("var");
       render("(");
       pp(_localvars.listlvar_, 0);
       render(")");
       render(":=");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.ListOutParams)
    {
       basil_ir.Absyn.ListOutParams _listoutparams = (basil_ir.Absyn.ListOutParams) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("(");
       pp(_listoutparams.listlvar_, 0);
       render(")");
       render(":=");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.Jump foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.GoTo)
    {
       basil_ir.Absyn.GoTo _goto = (basil_ir.Absyn.GoTo) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("goto");
       render("(");
       pp(_goto.listbident_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.Unreachable)
    {
       basil_ir.Absyn.Unreachable _unreachable = (basil_ir.Absyn.Unreachable) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("unreachable");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.Return)
    {
       basil_ir.Absyn.Return _return = (basil_ir.Absyn.Return) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("return");
       render("(");
       pp(_return.listexpr_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.LVar foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.LVarDef)
    {
       basil_ir.Absyn.LVarDef _lvardef = (basil_ir.Absyn.LVarDef) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("var");
       pp(_lvardef.bident_, 0);
       render(":");
       pp(_lvardef.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.GlobalLVar)
    {
       basil_ir.Absyn.GlobalLVar _globallvar = (basil_ir.Absyn.GlobalLVar) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_globallvar.bident_, 0);
       render(":");
       pp(_globallvar.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.ListLVar foo, int _i_)
  {
    ppListLVar(foo.iterator(), _i_);
  }

  private static void ppListLVar(java.util.Iterator<basil_ir.Absyn.LVar> it, int _i_)
  {
    if (it.hasNext())
    {
      basil_ir.Absyn.LVar el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListLVar(it, _i_);
      }
    }
  }


  private static void pp(basil_ir.Absyn.ListBlock foo, int _i_)
  {
    ppListBlock(foo.iterator(), _i_);
  }

  private static void ppListBlock(java.util.Iterator<basil_ir.Absyn.Block> it, int _i_)
  {
    if (it.hasNext())
    {
      basil_ir.Absyn.Block el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(";"); ppListBlock(it, _i_);
      }
    }
  }


  private static void pp(basil_ir.Absyn.Block foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.B)
    {
       basil_ir.Absyn.B _b = (basil_ir.Absyn.B) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("block");
       pp(_b.bident_, 0);
       pp(_b.addrattr_, 0);
       pp(_b.beginlist_, 0);
       pp(_b.liststatement_, 0);
       pp(_b.jump_, 0);
       pp(_b.endlist_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.PEntry foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.EntrySome)
    {
       basil_ir.Absyn.EntrySome _entrysome = (basil_ir.Absyn.EntrySome) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("entry_block");
       render("=");
       pp(_entrysome.str_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.EntryNone)
    {
       basil_ir.Absyn.EntryNone _entrynone = (basil_ir.Absyn.EntryNone) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.PAddress foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.AddrSome)
    {
       basil_ir.Absyn.AddrSome _addrsome = (basil_ir.Absyn.AddrSome) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("address");
       render("=");
       pp(_addrsome.intval_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.AddrNone)
    {
       basil_ir.Absyn.AddrNone _addrnone = (basil_ir.Absyn.AddrNone) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.InternalBlocks foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.BSome)
    {
       basil_ir.Absyn.BSome _bsome = (basil_ir.Absyn.BSome) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("blocks");
       render("=");
       pp(_bsome.beginlist_, 0);
       pp(_bsome.listblock_, 0);
       pp(_bsome.endlist_, 0);
       render(";");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BNone)
    {
       basil_ir.Absyn.BNone _bnone = (basil_ir.Absyn.BNone) foo;
       if (_i_ > 0) render(_L_PAREN);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.ProcDef foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.PD)
    {
       basil_ir.Absyn.PD _pd = (basil_ir.Absyn.PD) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_pd.beginrec_, 0);
       render("name");
       render("=");
       pp(_pd.str_, 0);
       render(";");
       pp(_pd.paddress_, 0);
       pp(_pd.pentry_, 0);
       pp(_pd.internalblocks_, 0);
       pp(_pd.endrec_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.Params foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.Param)
    {
       basil_ir.Absyn.Param _param = (basil_ir.Absyn.Param) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_param.bident_, 0);
       render(":");
       pp(_param.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.ListParams foo, int _i_)
  {
    ppListParams(foo.iterator(), _i_);
  }

  private static void ppListParams(java.util.Iterator<basil_ir.Absyn.Params> it, int _i_)
  {
    if (it.hasNext())
    {
      basil_ir.Absyn.Params el = it.next();
      if (!it.hasNext())
      { /* last */
        pp(el, _i_);
      }
      else
      { /* cons */
        pp(el, _i_); render(","); ppListParams(it, _i_);
      }
    }
  }


  private static void pp(basil_ir.Absyn.Expr foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.RVar)
    {
       basil_ir.Absyn.RVar _rvar = (basil_ir.Absyn.RVar) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_rvar.bident_, 0);
       render(":");
       pp(_rvar.type_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BinaryExpr)
    {
       basil_ir.Absyn.BinaryExpr _binaryexpr = (basil_ir.Absyn.BinaryExpr) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_binaryexpr.binop_, 0);
       render("(");
       pp(_binaryexpr.expr_1, 0);
       render(",");
       pp(_binaryexpr.expr_2, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.UnaryExpr)
    {
       basil_ir.Absyn.UnaryExpr _unaryexpr = (basil_ir.Absyn.UnaryExpr) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_unaryexpr.unop_, 0);
       render("(");
       pp(_unaryexpr.expr_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.ZeroExtend)
    {
       basil_ir.Absyn.ZeroExtend _zeroextend = (basil_ir.Absyn.ZeroExtend) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("zero_extend");
       render("(");
       pp(_zeroextend.intval_, 0);
       render(",");
       pp(_zeroextend.expr_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.SignExtend)
    {
       basil_ir.Absyn.SignExtend _signextend = (basil_ir.Absyn.SignExtend) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("sign_extend");
       render("(");
       pp(_signextend.intval_, 0);
       render(",");
       pp(_signextend.expr_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.Extract)
    {
       basil_ir.Absyn.Extract _extract = (basil_ir.Absyn.Extract) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("extract");
       render("(");
       pp(_extract.intval_1, 0);
       render(",");
       pp(_extract.intval_2, 0);
       render(",");
       pp(_extract.expr_, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.Concat)
    {
       basil_ir.Absyn.Concat _concat = (basil_ir.Absyn.Concat) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvconcat");
       render("(");
       pp(_concat.expr_1, 0);
       render(",");
       pp(_concat.expr_2, 0);
       render(")");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVLiteral)
    {
       basil_ir.Absyn.BVLiteral _bvliteral = (basil_ir.Absyn.BVLiteral) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_bvliteral.intval_, 0);
       render(":");
       pp(_bvliteral.bvtype_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.IntLiteral)
    {
       basil_ir.Absyn.IntLiteral _intliteral = (basil_ir.Absyn.IntLiteral) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_intliteral.intval_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.TrueLiteral)
    {
       basil_ir.Absyn.TrueLiteral _trueliteral = (basil_ir.Absyn.TrueLiteral) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("true");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.FalseLiteral)
    {
       basil_ir.Absyn.FalseLiteral _falseliteral = (basil_ir.Absyn.FalseLiteral) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("false");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.BinOp foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.BinOpBVBinOp)
    {
       basil_ir.Absyn.BinOpBVBinOp _binopbvbinop = (basil_ir.Absyn.BinOpBVBinOp) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_binopbvbinop.bvbinop_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BinOpBVLogicalBinOp)
    {
       basil_ir.Absyn.BinOpBVLogicalBinOp _binopbvlogicalbinop = (basil_ir.Absyn.BinOpBVLogicalBinOp) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_binopbvlogicalbinop.bvlogicalbinop_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BinOpBoolBinOp)
    {
       basil_ir.Absyn.BinOpBoolBinOp _binopboolbinop = (basil_ir.Absyn.BinOpBoolBinOp) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_binopboolbinop.boolbinop_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BinOpIntLogicalBinOp)
    {
       basil_ir.Absyn.BinOpIntLogicalBinOp _binopintlogicalbinop = (basil_ir.Absyn.BinOpIntLogicalBinOp) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_binopintlogicalbinop.intlogicalbinop_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BinOpIntBinOp)
    {
       basil_ir.Absyn.BinOpIntBinOp _binopintbinop = (basil_ir.Absyn.BinOpIntBinOp) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_binopintbinop.intbinop_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.UnOp foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.UnOpBVUnOp)
    {
       basil_ir.Absyn.UnOpBVUnOp _unopbvunop = (basil_ir.Absyn.UnOpBVUnOp) foo;
       if (_i_ > 0) render(_L_PAREN);
       pp(_unopbvunop.bvunop_, 0);
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.UnOp_boolnot)
    {
       basil_ir.Absyn.UnOp_boolnot _unop_boolnot = (basil_ir.Absyn.UnOp_boolnot) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("boolnot");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.UnOp_intneg)
    {
       basil_ir.Absyn.UnOp_intneg _unop_intneg = (basil_ir.Absyn.UnOp_intneg) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("intneg");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.BVUnOp foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.BVUnOp_bvnot)
    {
       basil_ir.Absyn.BVUnOp_bvnot _bvunop_bvnot = (basil_ir.Absyn.BVUnOp_bvnot) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvnot");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVUnOp_bvneg)
    {
       basil_ir.Absyn.BVUnOp_bvneg _bvunop_bvneg = (basil_ir.Absyn.BVUnOp_bvneg) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvneg");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.BVBinOp foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvand)
    {
       basil_ir.Absyn.BVBinOp_bvand _bvbinop_bvand = (basil_ir.Absyn.BVBinOp_bvand) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvand");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvor)
    {
       basil_ir.Absyn.BVBinOp_bvor _bvbinop_bvor = (basil_ir.Absyn.BVBinOp_bvor) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvor");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvadd)
    {
       basil_ir.Absyn.BVBinOp_bvadd _bvbinop_bvadd = (basil_ir.Absyn.BVBinOp_bvadd) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvadd");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvmul)
    {
       basil_ir.Absyn.BVBinOp_bvmul _bvbinop_bvmul = (basil_ir.Absyn.BVBinOp_bvmul) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvmul");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvudiv)
    {
       basil_ir.Absyn.BVBinOp_bvudiv _bvbinop_bvudiv = (basil_ir.Absyn.BVBinOp_bvudiv) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvudiv");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvurem)
    {
       basil_ir.Absyn.BVBinOp_bvurem _bvbinop_bvurem = (basil_ir.Absyn.BVBinOp_bvurem) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvurem");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvshl)
    {
       basil_ir.Absyn.BVBinOp_bvshl _bvbinop_bvshl = (basil_ir.Absyn.BVBinOp_bvshl) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvshl");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvlshr)
    {
       basil_ir.Absyn.BVBinOp_bvlshr _bvbinop_bvlshr = (basil_ir.Absyn.BVBinOp_bvlshr) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvlshr");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvult)
    {
       basil_ir.Absyn.BVBinOp_bvult _bvbinop_bvult = (basil_ir.Absyn.BVBinOp_bvult) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvult");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvnand)
    {
       basil_ir.Absyn.BVBinOp_bvnand _bvbinop_bvnand = (basil_ir.Absyn.BVBinOp_bvnand) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvnand");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvnor)
    {
       basil_ir.Absyn.BVBinOp_bvnor _bvbinop_bvnor = (basil_ir.Absyn.BVBinOp_bvnor) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvnor");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvxor)
    {
       basil_ir.Absyn.BVBinOp_bvxor _bvbinop_bvxor = (basil_ir.Absyn.BVBinOp_bvxor) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvxor");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvxnor)
    {
       basil_ir.Absyn.BVBinOp_bvxnor _bvbinop_bvxnor = (basil_ir.Absyn.BVBinOp_bvxnor) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvxnor");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvcomp)
    {
       basil_ir.Absyn.BVBinOp_bvcomp _bvbinop_bvcomp = (basil_ir.Absyn.BVBinOp_bvcomp) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvcomp");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvsub)
    {
       basil_ir.Absyn.BVBinOp_bvsub _bvbinop_bvsub = (basil_ir.Absyn.BVBinOp_bvsub) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvsub");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvsdiv)
    {
       basil_ir.Absyn.BVBinOp_bvsdiv _bvbinop_bvsdiv = (basil_ir.Absyn.BVBinOp_bvsdiv) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvsdiv");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvsrem)
    {
       basil_ir.Absyn.BVBinOp_bvsrem _bvbinop_bvsrem = (basil_ir.Absyn.BVBinOp_bvsrem) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvsrem");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvsmod)
    {
       basil_ir.Absyn.BVBinOp_bvsmod _bvbinop_bvsmod = (basil_ir.Absyn.BVBinOp_bvsmod) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvsmod");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVBinOp_bvashr)
    {
       basil_ir.Absyn.BVBinOp_bvashr _bvbinop_bvashr = (basil_ir.Absyn.BVBinOp_bvashr) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvashr");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.BVLogicalBinOp foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvule)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvule _bvlogicalbinop_bvule = (basil_ir.Absyn.BVLogicalBinOp_bvule) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvule");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvugt)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvugt _bvlogicalbinop_bvugt = (basil_ir.Absyn.BVLogicalBinOp_bvugt) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvugt");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvuge)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvuge _bvlogicalbinop_bvuge = (basil_ir.Absyn.BVLogicalBinOp_bvuge) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvuge");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvslt)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvslt _bvlogicalbinop_bvslt = (basil_ir.Absyn.BVLogicalBinOp_bvslt) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvslt");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvsle)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvsle _bvlogicalbinop_bvsle = (basil_ir.Absyn.BVLogicalBinOp_bvsle) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvsle");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvsgt)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvsgt _bvlogicalbinop_bvsgt = (basil_ir.Absyn.BVLogicalBinOp_bvsgt) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvsgt");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvsge)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvsge _bvlogicalbinop_bvsge = (basil_ir.Absyn.BVLogicalBinOp_bvsge) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvsge");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bveq)
    {
       basil_ir.Absyn.BVLogicalBinOp_bveq _bvlogicalbinop_bveq = (basil_ir.Absyn.BVLogicalBinOp_bveq) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bveq");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvneq)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvneq _bvlogicalbinop_bvneq = (basil_ir.Absyn.BVLogicalBinOp_bvneq) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("bvneq");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.IntBinOp foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.IntBinOp_intadd)
    {
       basil_ir.Absyn.IntBinOp_intadd _intbinop_intadd = (basil_ir.Absyn.IntBinOp_intadd) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("intadd");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.IntBinOp_intmul)
    {
       basil_ir.Absyn.IntBinOp_intmul _intbinop_intmul = (basil_ir.Absyn.IntBinOp_intmul) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("intmul");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.IntBinOp_intsub)
    {
       basil_ir.Absyn.IntBinOp_intsub _intbinop_intsub = (basil_ir.Absyn.IntBinOp_intsub) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("intsub");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.IntBinOp_intdiv)
    {
       basil_ir.Absyn.IntBinOp_intdiv _intbinop_intdiv = (basil_ir.Absyn.IntBinOp_intdiv) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("intdiv");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.IntBinOp_intmod)
    {
       basil_ir.Absyn.IntBinOp_intmod _intbinop_intmod = (basil_ir.Absyn.IntBinOp_intmod) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("intmod");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.IntLogicalBinOp foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_inteq)
    {
       basil_ir.Absyn.IntLogicalBinOp_inteq _intlogicalbinop_inteq = (basil_ir.Absyn.IntLogicalBinOp_inteq) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("inteq");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_intneq)
    {
       basil_ir.Absyn.IntLogicalBinOp_intneq _intlogicalbinop_intneq = (basil_ir.Absyn.IntLogicalBinOp_intneq) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("intneq");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_intlt)
    {
       basil_ir.Absyn.IntLogicalBinOp_intlt _intlogicalbinop_intlt = (basil_ir.Absyn.IntLogicalBinOp_intlt) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("intlt");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_intle)
    {
       basil_ir.Absyn.IntLogicalBinOp_intle _intlogicalbinop_intle = (basil_ir.Absyn.IntLogicalBinOp_intle) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("intle");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_intgt)
    {
       basil_ir.Absyn.IntLogicalBinOp_intgt _intlogicalbinop_intgt = (basil_ir.Absyn.IntLogicalBinOp_intgt) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("intgt");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_intge)
    {
       basil_ir.Absyn.IntLogicalBinOp_intge _intlogicalbinop_intge = (basil_ir.Absyn.IntLogicalBinOp_intge) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("intge");
       if (_i_ > 0) render(_R_PAREN);
    }

  }

  private static void pp(basil_ir.Absyn.BoolBinOp foo, int _i_)
  {
    if (foo instanceof basil_ir.Absyn.BoolBinOp_booleq)
    {
       basil_ir.Absyn.BoolBinOp_booleq _boolbinop_booleq = (basil_ir.Absyn.BoolBinOp_booleq) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("booleq");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BoolBinOp_boolneq)
    {
       basil_ir.Absyn.BoolBinOp_boolneq _boolbinop_boolneq = (basil_ir.Absyn.BoolBinOp_boolneq) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("boolneq");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BoolBinOp_booland)
    {
       basil_ir.Absyn.BoolBinOp_booland _boolbinop_booland = (basil_ir.Absyn.BoolBinOp_booland) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("booland");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BoolBinOp_boolor)
    {
       basil_ir.Absyn.BoolBinOp_boolor _boolbinop_boolor = (basil_ir.Absyn.BoolBinOp_boolor) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("boolor");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BoolBinOp_boolimplies)
    {
       basil_ir.Absyn.BoolBinOp_boolimplies _boolbinop_boolimplies = (basil_ir.Absyn.BoolBinOp_boolimplies) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("boolimplies");
       if (_i_ > 0) render(_R_PAREN);
    }
    else     if (foo instanceof basil_ir.Absyn.BoolBinOp_boolequiv)
    {
       basil_ir.Absyn.BoolBinOp_boolequiv _boolbinop_boolequiv = (basil_ir.Absyn.BoolBinOp_boolequiv) foo;
       if (_i_ > 0) render(_L_PAREN);
       render("boolequiv");
       if (_i_ > 0) render(_R_PAREN);
    }

  }


  private static void sh(basil_ir.Absyn.Program foo)
  {
    if (foo instanceof basil_ir.Absyn.Prog)
    {
       basil_ir.Absyn.Prog _prog = (basil_ir.Absyn.Prog) foo;
       render("(");
       render("Prog");
       render("[");
       sh(_prog.listdeclaration_);
       render("]");
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.ListDeclaration foo)
  {
     for (java.util.Iterator<basil_ir.Absyn.Declaration> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(basil_ir.Absyn.ListBIdent foo)
  {
     for (java.util.Iterator<String> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(basil_ir.Absyn.Declaration foo)
  {
    if (foo instanceof basil_ir.Absyn.LetDecl)
    {
       basil_ir.Absyn.LetDecl _letdecl = (basil_ir.Absyn.LetDecl) foo;
       render("(");
       render("LetDecl");
       sh(_letdecl.bident_);
       sh(_letdecl.mexpr_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.MemDecl)
    {
       basil_ir.Absyn.MemDecl _memdecl = (basil_ir.Absyn.MemDecl) foo;
       render("(");
       render("MemDecl");
       sh(_memdecl.bident_);
       sh(_memdecl.type_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.VarDecl)
    {
       basil_ir.Absyn.VarDecl _vardecl = (basil_ir.Absyn.VarDecl) foo;
       render("(");
       render("VarDecl");
       sh(_vardecl.bident_);
       sh(_vardecl.type_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.Procedure)
    {
       basil_ir.Absyn.Procedure _procedure = (basil_ir.Absyn.Procedure) foo;
       render("(");
       render("Procedure");
       sh(_procedure.bident_);
       render("[");
       sh(_procedure.listparams_1);
       render("]");
       render("[");
       sh(_procedure.listparams_2);
       render("]");
       sh(_procedure.procdef_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.MExpr foo)
  {
    if (foo instanceof basil_ir.Absyn.MSym)
    {
       basil_ir.Absyn.MSym _msym = (basil_ir.Absyn.MSym) foo;
       render("(");
       render("MSym");
       sh(_msym.bident_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.BlockM)
    {
       basil_ir.Absyn.BlockM _blockm = (basil_ir.Absyn.BlockM) foo;
       render("(");
       render("BlockM");
       sh(_blockm.block_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.IntType foo)
  {
    if (foo instanceof basil_ir.Absyn.IntT)
    {
       basil_ir.Absyn.IntT _intt = (basil_ir.Absyn.IntT) foo;
       render("IntT");
    }
  }

  private static void sh(basil_ir.Absyn.BoolType foo)
  {
    if (foo instanceof basil_ir.Absyn.BoolT)
    {
       basil_ir.Absyn.BoolT _boolt = (basil_ir.Absyn.BoolT) foo;
       render("BoolT");
    }
  }

  private static void sh(basil_ir.Absyn.MapType foo)
  {
    if (foo instanceof basil_ir.Absyn.MapT)
    {
       basil_ir.Absyn.MapT _mapt = (basil_ir.Absyn.MapT) foo;
       render("(");
       render("MapT");
       sh(_mapt.type_1);
       sh(_mapt.beginlist_);
       sh(_mapt.type_2);
       sh(_mapt.endlist_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.BVType foo)
  {
    if (foo instanceof basil_ir.Absyn.BVT)
    {
       basil_ir.Absyn.BVT _bvt = (basil_ir.Absyn.BVT) foo;
       render("(");
       render("BVT");
       sh(_bvt.bvtype_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.Type foo)
  {
    if (foo instanceof basil_ir.Absyn.TypeIntType)
    {
       basil_ir.Absyn.TypeIntType _typeinttype = (basil_ir.Absyn.TypeIntType) foo;
       render("(");
       render("TypeIntType");
       sh(_typeinttype.inttype_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.TypeBoolType)
    {
       basil_ir.Absyn.TypeBoolType _typebooltype = (basil_ir.Absyn.TypeBoolType) foo;
       render("(");
       render("TypeBoolType");
       sh(_typebooltype.booltype_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.TypeMapType)
    {
       basil_ir.Absyn.TypeMapType _typemaptype = (basil_ir.Absyn.TypeMapType) foo;
       render("(");
       render("TypeMapType");
       sh(_typemaptype.maptype_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.TypeBVType)
    {
       basil_ir.Absyn.TypeBVType _typebvtype = (basil_ir.Absyn.TypeBVType) foo;
       render("(");
       render("TypeBVType");
       sh(_typebvtype.bvtype_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.ListExpr foo)
  {
     for (java.util.Iterator<basil_ir.Absyn.Expr> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(basil_ir.Absyn.IntVal foo)
  {
    if (foo instanceof basil_ir.Absyn.HexInt)
    {
       basil_ir.Absyn.HexInt _hexint = (basil_ir.Absyn.HexInt) foo;
       render("(");
       render("HexInt");
       sh(_hexint.integerhex_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.DecInt)
    {
       basil_ir.Absyn.DecInt _decint = (basil_ir.Absyn.DecInt) foo;
       render("(");
       render("DecInt");
       sh(_decint.integer_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.AddrAttr foo)
  {
    if (foo instanceof basil_ir.Absyn.AddrAttrSome)
    {
       basil_ir.Absyn.AddrAttrSome _addrattrsome = (basil_ir.Absyn.AddrAttrSome) foo;
       render("(");
       render("AddrAttrSome");
       sh(_addrattrsome.beginrec_);
       sh(_addrattrsome.intval_);
       sh(_addrattrsome.endrec_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.AddrAttrNone)
    {
       basil_ir.Absyn.AddrAttrNone _addrattrnone = (basil_ir.Absyn.AddrAttrNone) foo;
       render("AddrAttrNone");
    }
    if (foo instanceof basil_ir.Absyn.AddrAttrEmpty)
    {
       basil_ir.Absyn.AddrAttrEmpty _addrattrempty = (basil_ir.Absyn.AddrAttrEmpty) foo;
       render("(");
       render("AddrAttrEmpty");
       sh(_addrattrempty.beginrec_);
       sh(_addrattrempty.endrec_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.Endian foo)
  {
    if (foo instanceof basil_ir.Absyn.LittleEndian)
    {
       basil_ir.Absyn.LittleEndian _littleendian = (basil_ir.Absyn.LittleEndian) foo;
       render("LittleEndian");
    }
    if (foo instanceof basil_ir.Absyn.BigEndian)
    {
       basil_ir.Absyn.BigEndian _bigendian = (basil_ir.Absyn.BigEndian) foo;
       render("BigEndian");
    }
  }

  private static void sh(basil_ir.Absyn.ListStatement foo)
  {
     for (java.util.Iterator<basil_ir.Absyn.Statement> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(basil_ir.Absyn.Statement foo)
  {
    if (foo instanceof basil_ir.Absyn.Assign)
    {
       basil_ir.Absyn.Assign _assign = (basil_ir.Absyn.Assign) foo;
       render("(");
       render("Assign");
       sh(_assign.lvar_);
       sh(_assign.expr_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.SLoad)
    {
       basil_ir.Absyn.SLoad _sload = (basil_ir.Absyn.SLoad) foo;
       render("(");
       render("SLoad");
       sh(_sload.lvar_);
       sh(_sload.endian_);
       sh(_sload.bident_);
       sh(_sload.expr_);
       sh(_sload.intval_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.SStore)
    {
       basil_ir.Absyn.SStore _sstore = (basil_ir.Absyn.SStore) foo;
       render("(");
       render("SStore");
       sh(_sstore.endian_);
       sh(_sstore.bident_);
       sh(_sstore.expr_1);
       sh(_sstore.expr_2);
       sh(_sstore.intval_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.DirectCall)
    {
       basil_ir.Absyn.DirectCall _directcall = (basil_ir.Absyn.DirectCall) foo;
       render("(");
       render("DirectCall");
       sh(_directcall.calllvars_);
       sh(_directcall.bident_);
       render("[");
       sh(_directcall.listexpr_);
       render("]");
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.IndirectCall)
    {
       basil_ir.Absyn.IndirectCall _indirectcall = (basil_ir.Absyn.IndirectCall) foo;
       render("(");
       render("IndirectCall");
       sh(_indirectcall.expr_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.Assume)
    {
       basil_ir.Absyn.Assume _assume = (basil_ir.Absyn.Assume) foo;
       render("(");
       render("Assume");
       sh(_assume.expr_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.Assert)
    {
       basil_ir.Absyn.Assert _assert = (basil_ir.Absyn.Assert) foo;
       render("(");
       render("Assert");
       sh(_assert.expr_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.CallLVars foo)
  {
    if (foo instanceof basil_ir.Absyn.NoOutParams)
    {
       basil_ir.Absyn.NoOutParams _nooutparams = (basil_ir.Absyn.NoOutParams) foo;
       render("NoOutParams");
    }
    if (foo instanceof basil_ir.Absyn.LocalVars)
    {
       basil_ir.Absyn.LocalVars _localvars = (basil_ir.Absyn.LocalVars) foo;
       render("(");
       render("LocalVars");
       render("[");
       sh(_localvars.listlvar_);
       render("]");
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.ListOutParams)
    {
       basil_ir.Absyn.ListOutParams _listoutparams = (basil_ir.Absyn.ListOutParams) foo;
       render("(");
       render("ListOutParams");
       render("[");
       sh(_listoutparams.listlvar_);
       render("]");
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.Jump foo)
  {
    if (foo instanceof basil_ir.Absyn.GoTo)
    {
       basil_ir.Absyn.GoTo _goto = (basil_ir.Absyn.GoTo) foo;
       render("(");
       render("GoTo");
       render("[");
       sh(_goto.listbident_);
       render("]");
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.Unreachable)
    {
       basil_ir.Absyn.Unreachable _unreachable = (basil_ir.Absyn.Unreachable) foo;
       render("Unreachable");
    }
    if (foo instanceof basil_ir.Absyn.Return)
    {
       basil_ir.Absyn.Return _return = (basil_ir.Absyn.Return) foo;
       render("(");
       render("Return");
       render("[");
       sh(_return.listexpr_);
       render("]");
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.LVar foo)
  {
    if (foo instanceof basil_ir.Absyn.LVarDef)
    {
       basil_ir.Absyn.LVarDef _lvardef = (basil_ir.Absyn.LVarDef) foo;
       render("(");
       render("LVarDef");
       sh(_lvardef.bident_);
       sh(_lvardef.type_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.GlobalLVar)
    {
       basil_ir.Absyn.GlobalLVar _globallvar = (basil_ir.Absyn.GlobalLVar) foo;
       render("(");
       render("GlobalLVar");
       sh(_globallvar.bident_);
       sh(_globallvar.type_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.ListLVar foo)
  {
     for (java.util.Iterator<basil_ir.Absyn.LVar> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(basil_ir.Absyn.ListBlock foo)
  {
     for (java.util.Iterator<basil_ir.Absyn.Block> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(basil_ir.Absyn.Block foo)
  {
    if (foo instanceof basil_ir.Absyn.B)
    {
       basil_ir.Absyn.B _b = (basil_ir.Absyn.B) foo;
       render("(");
       render("B");
       sh(_b.bident_);
       sh(_b.addrattr_);
       sh(_b.beginlist_);
       render("[");
       sh(_b.liststatement_);
       render("]");
       sh(_b.jump_);
       sh(_b.endlist_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.PEntry foo)
  {
    if (foo instanceof basil_ir.Absyn.EntrySome)
    {
       basil_ir.Absyn.EntrySome _entrysome = (basil_ir.Absyn.EntrySome) foo;
       render("(");
       render("EntrySome");
       sh(_entrysome.str_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.EntryNone)
    {
       basil_ir.Absyn.EntryNone _entrynone = (basil_ir.Absyn.EntryNone) foo;
       render("EntryNone");
    }
  }

  private static void sh(basil_ir.Absyn.PAddress foo)
  {
    if (foo instanceof basil_ir.Absyn.AddrSome)
    {
       basil_ir.Absyn.AddrSome _addrsome = (basil_ir.Absyn.AddrSome) foo;
       render("(");
       render("AddrSome");
       sh(_addrsome.intval_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.AddrNone)
    {
       basil_ir.Absyn.AddrNone _addrnone = (basil_ir.Absyn.AddrNone) foo;
       render("AddrNone");
    }
  }

  private static void sh(basil_ir.Absyn.InternalBlocks foo)
  {
    if (foo instanceof basil_ir.Absyn.BSome)
    {
       basil_ir.Absyn.BSome _bsome = (basil_ir.Absyn.BSome) foo;
       render("(");
       render("BSome");
       sh(_bsome.beginlist_);
       render("[");
       sh(_bsome.listblock_);
       render("]");
       sh(_bsome.endlist_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.BNone)
    {
       basil_ir.Absyn.BNone _bnone = (basil_ir.Absyn.BNone) foo;
       render("BNone");
    }
  }

  private static void sh(basil_ir.Absyn.ProcDef foo)
  {
    if (foo instanceof basil_ir.Absyn.PD)
    {
       basil_ir.Absyn.PD _pd = (basil_ir.Absyn.PD) foo;
       render("(");
       render("PD");
       sh(_pd.beginrec_);
       sh(_pd.str_);
       sh(_pd.paddress_);
       sh(_pd.pentry_);
       sh(_pd.internalblocks_);
       sh(_pd.endrec_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.Params foo)
  {
    if (foo instanceof basil_ir.Absyn.Param)
    {
       basil_ir.Absyn.Param _param = (basil_ir.Absyn.Param) foo;
       render("(");
       render("Param");
       sh(_param.bident_);
       sh(_param.type_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.ListParams foo)
  {
     for (java.util.Iterator<basil_ir.Absyn.Params> it = foo.iterator(); it.hasNext();)
     {
       sh(it.next());
       if (it.hasNext())
         render(",");
     }
  }

  private static void sh(basil_ir.Absyn.Expr foo)
  {
    if (foo instanceof basil_ir.Absyn.RVar)
    {
       basil_ir.Absyn.RVar _rvar = (basil_ir.Absyn.RVar) foo;
       render("(");
       render("RVar");
       sh(_rvar.bident_);
       sh(_rvar.type_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.BinaryExpr)
    {
       basil_ir.Absyn.BinaryExpr _binaryexpr = (basil_ir.Absyn.BinaryExpr) foo;
       render("(");
       render("BinaryExpr");
       sh(_binaryexpr.binop_);
       sh(_binaryexpr.expr_1);
       sh(_binaryexpr.expr_2);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.UnaryExpr)
    {
       basil_ir.Absyn.UnaryExpr _unaryexpr = (basil_ir.Absyn.UnaryExpr) foo;
       render("(");
       render("UnaryExpr");
       sh(_unaryexpr.unop_);
       sh(_unaryexpr.expr_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.ZeroExtend)
    {
       basil_ir.Absyn.ZeroExtend _zeroextend = (basil_ir.Absyn.ZeroExtend) foo;
       render("(");
       render("ZeroExtend");
       sh(_zeroextend.intval_);
       sh(_zeroextend.expr_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.SignExtend)
    {
       basil_ir.Absyn.SignExtend _signextend = (basil_ir.Absyn.SignExtend) foo;
       render("(");
       render("SignExtend");
       sh(_signextend.intval_);
       sh(_signextend.expr_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.Extract)
    {
       basil_ir.Absyn.Extract _extract = (basil_ir.Absyn.Extract) foo;
       render("(");
       render("Extract");
       sh(_extract.intval_1);
       sh(_extract.intval_2);
       sh(_extract.expr_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.Concat)
    {
       basil_ir.Absyn.Concat _concat = (basil_ir.Absyn.Concat) foo;
       render("(");
       render("Concat");
       sh(_concat.expr_1);
       sh(_concat.expr_2);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.BVLiteral)
    {
       basil_ir.Absyn.BVLiteral _bvliteral = (basil_ir.Absyn.BVLiteral) foo;
       render("(");
       render("BVLiteral");
       sh(_bvliteral.intval_);
       sh(_bvliteral.bvtype_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.IntLiteral)
    {
       basil_ir.Absyn.IntLiteral _intliteral = (basil_ir.Absyn.IntLiteral) foo;
       render("(");
       render("IntLiteral");
       sh(_intliteral.intval_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.TrueLiteral)
    {
       basil_ir.Absyn.TrueLiteral _trueliteral = (basil_ir.Absyn.TrueLiteral) foo;
       render("TrueLiteral");
    }
    if (foo instanceof basil_ir.Absyn.FalseLiteral)
    {
       basil_ir.Absyn.FalseLiteral _falseliteral = (basil_ir.Absyn.FalseLiteral) foo;
       render("FalseLiteral");
    }
  }

  private static void sh(basil_ir.Absyn.BinOp foo)
  {
    if (foo instanceof basil_ir.Absyn.BinOpBVBinOp)
    {
       basil_ir.Absyn.BinOpBVBinOp _binopbvbinop = (basil_ir.Absyn.BinOpBVBinOp) foo;
       render("(");
       render("BinOpBVBinOp");
       sh(_binopbvbinop.bvbinop_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.BinOpBVLogicalBinOp)
    {
       basil_ir.Absyn.BinOpBVLogicalBinOp _binopbvlogicalbinop = (basil_ir.Absyn.BinOpBVLogicalBinOp) foo;
       render("(");
       render("BinOpBVLogicalBinOp");
       sh(_binopbvlogicalbinop.bvlogicalbinop_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.BinOpBoolBinOp)
    {
       basil_ir.Absyn.BinOpBoolBinOp _binopboolbinop = (basil_ir.Absyn.BinOpBoolBinOp) foo;
       render("(");
       render("BinOpBoolBinOp");
       sh(_binopboolbinop.boolbinop_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.BinOpIntLogicalBinOp)
    {
       basil_ir.Absyn.BinOpIntLogicalBinOp _binopintlogicalbinop = (basil_ir.Absyn.BinOpIntLogicalBinOp) foo;
       render("(");
       render("BinOpIntLogicalBinOp");
       sh(_binopintlogicalbinop.intlogicalbinop_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.BinOpIntBinOp)
    {
       basil_ir.Absyn.BinOpIntBinOp _binopintbinop = (basil_ir.Absyn.BinOpIntBinOp) foo;
       render("(");
       render("BinOpIntBinOp");
       sh(_binopintbinop.intbinop_);
       render(")");
    }
  }

  private static void sh(basil_ir.Absyn.UnOp foo)
  {
    if (foo instanceof basil_ir.Absyn.UnOpBVUnOp)
    {
       basil_ir.Absyn.UnOpBVUnOp _unopbvunop = (basil_ir.Absyn.UnOpBVUnOp) foo;
       render("(");
       render("UnOpBVUnOp");
       sh(_unopbvunop.bvunop_);
       render(")");
    }
    if (foo instanceof basil_ir.Absyn.UnOp_boolnot)
    {
       basil_ir.Absyn.UnOp_boolnot _unop_boolnot = (basil_ir.Absyn.UnOp_boolnot) foo;
       render("UnOp_boolnot");
    }
    if (foo instanceof basil_ir.Absyn.UnOp_intneg)
    {
       basil_ir.Absyn.UnOp_intneg _unop_intneg = (basil_ir.Absyn.UnOp_intneg) foo;
       render("UnOp_intneg");
    }
  }

  private static void sh(basil_ir.Absyn.BVUnOp foo)
  {
    if (foo instanceof basil_ir.Absyn.BVUnOp_bvnot)
    {
       basil_ir.Absyn.BVUnOp_bvnot _bvunop_bvnot = (basil_ir.Absyn.BVUnOp_bvnot) foo;
       render("BVUnOp_bvnot");
    }
    if (foo instanceof basil_ir.Absyn.BVUnOp_bvneg)
    {
       basil_ir.Absyn.BVUnOp_bvneg _bvunop_bvneg = (basil_ir.Absyn.BVUnOp_bvneg) foo;
       render("BVUnOp_bvneg");
    }
  }

  private static void sh(basil_ir.Absyn.BVBinOp foo)
  {
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvand)
    {
       basil_ir.Absyn.BVBinOp_bvand _bvbinop_bvand = (basil_ir.Absyn.BVBinOp_bvand) foo;
       render("BVBinOp_bvand");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvor)
    {
       basil_ir.Absyn.BVBinOp_bvor _bvbinop_bvor = (basil_ir.Absyn.BVBinOp_bvor) foo;
       render("BVBinOp_bvor");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvadd)
    {
       basil_ir.Absyn.BVBinOp_bvadd _bvbinop_bvadd = (basil_ir.Absyn.BVBinOp_bvadd) foo;
       render("BVBinOp_bvadd");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvmul)
    {
       basil_ir.Absyn.BVBinOp_bvmul _bvbinop_bvmul = (basil_ir.Absyn.BVBinOp_bvmul) foo;
       render("BVBinOp_bvmul");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvudiv)
    {
       basil_ir.Absyn.BVBinOp_bvudiv _bvbinop_bvudiv = (basil_ir.Absyn.BVBinOp_bvudiv) foo;
       render("BVBinOp_bvudiv");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvurem)
    {
       basil_ir.Absyn.BVBinOp_bvurem _bvbinop_bvurem = (basil_ir.Absyn.BVBinOp_bvurem) foo;
       render("BVBinOp_bvurem");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvshl)
    {
       basil_ir.Absyn.BVBinOp_bvshl _bvbinop_bvshl = (basil_ir.Absyn.BVBinOp_bvshl) foo;
       render("BVBinOp_bvshl");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvlshr)
    {
       basil_ir.Absyn.BVBinOp_bvlshr _bvbinop_bvlshr = (basil_ir.Absyn.BVBinOp_bvlshr) foo;
       render("BVBinOp_bvlshr");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvult)
    {
       basil_ir.Absyn.BVBinOp_bvult _bvbinop_bvult = (basil_ir.Absyn.BVBinOp_bvult) foo;
       render("BVBinOp_bvult");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvnand)
    {
       basil_ir.Absyn.BVBinOp_bvnand _bvbinop_bvnand = (basil_ir.Absyn.BVBinOp_bvnand) foo;
       render("BVBinOp_bvnand");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvnor)
    {
       basil_ir.Absyn.BVBinOp_bvnor _bvbinop_bvnor = (basil_ir.Absyn.BVBinOp_bvnor) foo;
       render("BVBinOp_bvnor");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvxor)
    {
       basil_ir.Absyn.BVBinOp_bvxor _bvbinop_bvxor = (basil_ir.Absyn.BVBinOp_bvxor) foo;
       render("BVBinOp_bvxor");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvxnor)
    {
       basil_ir.Absyn.BVBinOp_bvxnor _bvbinop_bvxnor = (basil_ir.Absyn.BVBinOp_bvxnor) foo;
       render("BVBinOp_bvxnor");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvcomp)
    {
       basil_ir.Absyn.BVBinOp_bvcomp _bvbinop_bvcomp = (basil_ir.Absyn.BVBinOp_bvcomp) foo;
       render("BVBinOp_bvcomp");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvsub)
    {
       basil_ir.Absyn.BVBinOp_bvsub _bvbinop_bvsub = (basil_ir.Absyn.BVBinOp_bvsub) foo;
       render("BVBinOp_bvsub");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvsdiv)
    {
       basil_ir.Absyn.BVBinOp_bvsdiv _bvbinop_bvsdiv = (basil_ir.Absyn.BVBinOp_bvsdiv) foo;
       render("BVBinOp_bvsdiv");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvsrem)
    {
       basil_ir.Absyn.BVBinOp_bvsrem _bvbinop_bvsrem = (basil_ir.Absyn.BVBinOp_bvsrem) foo;
       render("BVBinOp_bvsrem");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvsmod)
    {
       basil_ir.Absyn.BVBinOp_bvsmod _bvbinop_bvsmod = (basil_ir.Absyn.BVBinOp_bvsmod) foo;
       render("BVBinOp_bvsmod");
    }
    if (foo instanceof basil_ir.Absyn.BVBinOp_bvashr)
    {
       basil_ir.Absyn.BVBinOp_bvashr _bvbinop_bvashr = (basil_ir.Absyn.BVBinOp_bvashr) foo;
       render("BVBinOp_bvashr");
    }
  }

  private static void sh(basil_ir.Absyn.BVLogicalBinOp foo)
  {
    if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvule)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvule _bvlogicalbinop_bvule = (basil_ir.Absyn.BVLogicalBinOp_bvule) foo;
       render("BVLogicalBinOp_bvule");
    }
    if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvugt)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvugt _bvlogicalbinop_bvugt = (basil_ir.Absyn.BVLogicalBinOp_bvugt) foo;
       render("BVLogicalBinOp_bvugt");
    }
    if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvuge)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvuge _bvlogicalbinop_bvuge = (basil_ir.Absyn.BVLogicalBinOp_bvuge) foo;
       render("BVLogicalBinOp_bvuge");
    }
    if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvslt)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvslt _bvlogicalbinop_bvslt = (basil_ir.Absyn.BVLogicalBinOp_bvslt) foo;
       render("BVLogicalBinOp_bvslt");
    }
    if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvsle)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvsle _bvlogicalbinop_bvsle = (basil_ir.Absyn.BVLogicalBinOp_bvsle) foo;
       render("BVLogicalBinOp_bvsle");
    }
    if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvsgt)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvsgt _bvlogicalbinop_bvsgt = (basil_ir.Absyn.BVLogicalBinOp_bvsgt) foo;
       render("BVLogicalBinOp_bvsgt");
    }
    if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvsge)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvsge _bvlogicalbinop_bvsge = (basil_ir.Absyn.BVLogicalBinOp_bvsge) foo;
       render("BVLogicalBinOp_bvsge");
    }
    if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bveq)
    {
       basil_ir.Absyn.BVLogicalBinOp_bveq _bvlogicalbinop_bveq = (basil_ir.Absyn.BVLogicalBinOp_bveq) foo;
       render("BVLogicalBinOp_bveq");
    }
    if (foo instanceof basil_ir.Absyn.BVLogicalBinOp_bvneq)
    {
       basil_ir.Absyn.BVLogicalBinOp_bvneq _bvlogicalbinop_bvneq = (basil_ir.Absyn.BVLogicalBinOp_bvneq) foo;
       render("BVLogicalBinOp_bvneq");
    }
  }

  private static void sh(basil_ir.Absyn.IntBinOp foo)
  {
    if (foo instanceof basil_ir.Absyn.IntBinOp_intadd)
    {
       basil_ir.Absyn.IntBinOp_intadd _intbinop_intadd = (basil_ir.Absyn.IntBinOp_intadd) foo;
       render("IntBinOp_intadd");
    }
    if (foo instanceof basil_ir.Absyn.IntBinOp_intmul)
    {
       basil_ir.Absyn.IntBinOp_intmul _intbinop_intmul = (basil_ir.Absyn.IntBinOp_intmul) foo;
       render("IntBinOp_intmul");
    }
    if (foo instanceof basil_ir.Absyn.IntBinOp_intsub)
    {
       basil_ir.Absyn.IntBinOp_intsub _intbinop_intsub = (basil_ir.Absyn.IntBinOp_intsub) foo;
       render("IntBinOp_intsub");
    }
    if (foo instanceof basil_ir.Absyn.IntBinOp_intdiv)
    {
       basil_ir.Absyn.IntBinOp_intdiv _intbinop_intdiv = (basil_ir.Absyn.IntBinOp_intdiv) foo;
       render("IntBinOp_intdiv");
    }
    if (foo instanceof basil_ir.Absyn.IntBinOp_intmod)
    {
       basil_ir.Absyn.IntBinOp_intmod _intbinop_intmod = (basil_ir.Absyn.IntBinOp_intmod) foo;
       render("IntBinOp_intmod");
    }
  }

  private static void sh(basil_ir.Absyn.IntLogicalBinOp foo)
  {
    if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_inteq)
    {
       basil_ir.Absyn.IntLogicalBinOp_inteq _intlogicalbinop_inteq = (basil_ir.Absyn.IntLogicalBinOp_inteq) foo;
       render("IntLogicalBinOp_inteq");
    }
    if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_intneq)
    {
       basil_ir.Absyn.IntLogicalBinOp_intneq _intlogicalbinop_intneq = (basil_ir.Absyn.IntLogicalBinOp_intneq) foo;
       render("IntLogicalBinOp_intneq");
    }
    if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_intlt)
    {
       basil_ir.Absyn.IntLogicalBinOp_intlt _intlogicalbinop_intlt = (basil_ir.Absyn.IntLogicalBinOp_intlt) foo;
       render("IntLogicalBinOp_intlt");
    }
    if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_intle)
    {
       basil_ir.Absyn.IntLogicalBinOp_intle _intlogicalbinop_intle = (basil_ir.Absyn.IntLogicalBinOp_intle) foo;
       render("IntLogicalBinOp_intle");
    }
    if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_intgt)
    {
       basil_ir.Absyn.IntLogicalBinOp_intgt _intlogicalbinop_intgt = (basil_ir.Absyn.IntLogicalBinOp_intgt) foo;
       render("IntLogicalBinOp_intgt");
    }
    if (foo instanceof basil_ir.Absyn.IntLogicalBinOp_intge)
    {
       basil_ir.Absyn.IntLogicalBinOp_intge _intlogicalbinop_intge = (basil_ir.Absyn.IntLogicalBinOp_intge) foo;
       render("IntLogicalBinOp_intge");
    }
  }

  private static void sh(basil_ir.Absyn.BoolBinOp foo)
  {
    if (foo instanceof basil_ir.Absyn.BoolBinOp_booleq)
    {
       basil_ir.Absyn.BoolBinOp_booleq _boolbinop_booleq = (basil_ir.Absyn.BoolBinOp_booleq) foo;
       render("BoolBinOp_booleq");
    }
    if (foo instanceof basil_ir.Absyn.BoolBinOp_boolneq)
    {
       basil_ir.Absyn.BoolBinOp_boolneq _boolbinop_boolneq = (basil_ir.Absyn.BoolBinOp_boolneq) foo;
       render("BoolBinOp_boolneq");
    }
    if (foo instanceof basil_ir.Absyn.BoolBinOp_booland)
    {
       basil_ir.Absyn.BoolBinOp_booland _boolbinop_booland = (basil_ir.Absyn.BoolBinOp_booland) foo;
       render("BoolBinOp_booland");
    }
    if (foo instanceof basil_ir.Absyn.BoolBinOp_boolor)
    {
       basil_ir.Absyn.BoolBinOp_boolor _boolbinop_boolor = (basil_ir.Absyn.BoolBinOp_boolor) foo;
       render("BoolBinOp_boolor");
    }
    if (foo instanceof basil_ir.Absyn.BoolBinOp_boolimplies)
    {
       basil_ir.Absyn.BoolBinOp_boolimplies _boolbinop_boolimplies = (basil_ir.Absyn.BoolBinOp_boolimplies) foo;
       render("BoolBinOp_boolimplies");
    }
    if (foo instanceof basil_ir.Absyn.BoolBinOp_boolequiv)
    {
       basil_ir.Absyn.BoolBinOp_boolequiv _boolbinop_boolequiv = (basil_ir.Absyn.BoolBinOp_boolequiv) foo;
       render("BoolBinOp_boolequiv");
    }
  }


  private static void pp(Integer n, int _i_) { buf_.append(n); buf_.append(" "); }
  private static void pp(Double d, int _i_) { buf_.append(String.format(java.util.Locale.ROOT, "%.15g ", d)); }
  private static void pp(String s, int _i_) { buf_.append(s); buf_.append(" "); }
  private static void pp(Character c, int _i_) { buf_.append("'" + escape(c.toString()) + "'"); buf_.append(" "); }
  private static void sh(Integer n) { render(n.toString()); }
  private static void sh(Double d) { render(String.format(java.util.Locale.ROOT, "%.15g", d)); }
  private static void sh(Character c) { render("'" + escape(c.toString()) + "'"); }
  private static void sh(String s) { printQuoted(s); }

  private static void printQuoted(String s) { render("\"" + escape(s) + "\""); }

  public static String escape(String s) {
    if (s == null) return null;
    return s.replace("\\", "\\\\")
            .replace("\t", "\\t")
            .replace("\b", "\\b")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\f", "\\f")
            .replace("\"", "\\\"");
  }

  private static void indent()
  {
    int n = _n_;
    while (n > 0)
    {
      buf_.append(' ');
      n--;
    }
  }

  private static void backup()
  {
    int prev = buf_.length() - 1;
    if (prev >= 0 && buf_.charAt(prev) == ' ')
      buf_.setLength(prev);
  }

  private static void trim()
  {
    // Trim initial spaces
    int end = 0;
    int len = buf_.length();
    while (end < len && buf_.charAt(end) == ' ')
      end++;
    buf_.delete(0, end);
    // Trim trailing spaces
    removeTrailingSpaces();
  }

  private static void removeTrailingSpaces()
  {
    int end = buf_.length();
    while (end > 0 && buf_.charAt(end-1) == ' ')
      end--;
    buf_.setLength(end);
  }

  private static void removeTrailingWhitespace()
  {
    int end = buf_.length();
    while (end > 0 && (buf_.charAt(end-1) == ' ' || buf_.charAt(end-1) == '\n'))
      end--;
    buf_.setLength(end);
  }

  private static void onEmptyLine()
  {
    removeTrailingSpaces();
    int len = buf_.length();
    if (len > 0 && buf_.charAt(len-1) != '\n') buf_.append("\n");
    indent();
  }

  private static int _n_ = 0;
  private static StringBuilder buf_ = new StringBuilder(INITIAL_BUFFER_SIZE);
}

