// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir;

/*** Visitor Design Pattern Skeleton. ***/

/* This implements the common visitor design pattern.
   Tests show it to be slightly less efficient than the
   instanceof method, but easier to use.
   Replace the R and A parameters with the desired return
   and context types.*/

public class VisitSkel
{
  public class ProgramVisitor<R,A> implements basil_ir.Absyn.Program.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.Prog p, A arg)
    { /* Code for Prog goes here */
      for (basil_ir.Absyn.Declaration x: p.listdeclaration_) {
        x.accept(new DeclarationVisitor<R,A>(), arg);
      }
      return null;
    }
  }
  public class DeclarationVisitor<R,A> implements basil_ir.Absyn.Declaration.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.LetDecl p, A arg)
    { /* Code for LetDecl goes here */
      //p.bident_;
      p.mexpr_.accept(new MExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.MemDecl p, A arg)
    { /* Code for MemDecl goes here */
      //p.bident_;
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.VarDecl p, A arg)
    { /* Code for VarDecl goes here */
      //p.bident_;
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.Procedure p, A arg)
    { /* Code for Procedure goes here */
      //p.bident_;
      for (basil_ir.Absyn.Params x: p.listparams_1) {
        x.accept(new ParamsVisitor<R,A>(), arg);
      }
      for (basil_ir.Absyn.Params x: p.listparams_2) {
        x.accept(new ParamsVisitor<R,A>(), arg);
      }
      p.procdef_.accept(new ProcDefVisitor<R,A>(), arg);
      return null;
    }
  }
  public class MExprVisitor<R,A> implements basil_ir.Absyn.MExpr.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.MSym p, A arg)
    { /* Code for MSym goes here */
      //p.bident_;
      return null;
    }
    public R visit(basil_ir.Absyn.BlockM p, A arg)
    { /* Code for BlockM goes here */
      p.block_.accept(new BlockVisitor<R,A>(), arg);
      return null;
    }
  }
  public class IntTypeVisitor<R,A> implements basil_ir.Absyn.IntType.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.IntT p, A arg)
    { /* Code for IntT goes here */
      return null;
    }
  }
  public class BoolTypeVisitor<R,A> implements basil_ir.Absyn.BoolType.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.BoolT p, A arg)
    { /* Code for BoolT goes here */
      return null;
    }
  }
  public class MapTypeVisitor<R,A> implements basil_ir.Absyn.MapType.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.MapT p, A arg)
    { /* Code for MapT goes here */
      p.type_1.accept(new TypeVisitor<R,A>(), arg);
      //p.beginlist_;
      p.type_2.accept(new TypeVisitor<R,A>(), arg);
      //p.endlist_;
      return null;
    }
  }
  public class BVTypeVisitor<R,A> implements basil_ir.Absyn.BVType.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.BVT p, A arg)
    { /* Code for BVT goes here */
      //p.bvtype_;
      return null;
    }
  }
  public class TypeVisitor<R,A> implements basil_ir.Absyn.Type.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.TypeIntType p, A arg)
    { /* Code for TypeIntType goes here */
      p.inttype_.accept(new IntTypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.TypeBoolType p, A arg)
    { /* Code for TypeBoolType goes here */
      p.booltype_.accept(new BoolTypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.TypeMapType p, A arg)
    { /* Code for TypeMapType goes here */
      p.maptype_.accept(new MapTypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.TypeBVType p, A arg)
    { /* Code for TypeBVType goes here */
      p.bvtype_.accept(new BVTypeVisitor<R,A>(), arg);
      return null;
    }
  }
  public class IntValVisitor<R,A> implements basil_ir.Absyn.IntVal.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.HexInt p, A arg)
    { /* Code for HexInt goes here */
      //p.integerhex_;
      return null;
    }
    public R visit(basil_ir.Absyn.DecInt p, A arg)
    { /* Code for DecInt goes here */
      //p.integer_;
      return null;
    }
  }
  public class AddrAttrVisitor<R,A> implements basil_ir.Absyn.AddrAttr.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.AddrAttrSome p, A arg)
    { /* Code for AddrAttrSome goes here */
      //p.beginrec_;
      p.intval_.accept(new IntValVisitor<R,A>(), arg);
      //p.endrec_;
      return null;
    }
    public R visit(basil_ir.Absyn.AddrAttrNone p, A arg)
    { /* Code for AddrAttrNone goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.AddrAttrEmpty p, A arg)
    { /* Code for AddrAttrEmpty goes here */
      //p.beginrec_;
      //p.endrec_;
      return null;
    }
  }
  public class EndianVisitor<R,A> implements basil_ir.Absyn.Endian.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.LittleEndian p, A arg)
    { /* Code for LittleEndian goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BigEndian p, A arg)
    { /* Code for BigEndian goes here */
      return null;
    }
  }
  public class StatementVisitor<R,A> implements basil_ir.Absyn.Statement.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.Assign p, A arg)
    { /* Code for Assign goes here */
      p.lvar_.accept(new LVarVisitor<R,A>(), arg);
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.SLoad p, A arg)
    { /* Code for SLoad goes here */
      p.lvar_.accept(new LVarVisitor<R,A>(), arg);
      p.endian_.accept(new EndianVisitor<R,A>(), arg);
      //p.bident_;
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      p.intval_.accept(new IntValVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.SStore p, A arg)
    { /* Code for SStore goes here */
      p.endian_.accept(new EndianVisitor<R,A>(), arg);
      //p.bident_;
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      p.intval_.accept(new IntValVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.DirectCall p, A arg)
    { /* Code for DirectCall goes here */
      p.calllvars_.accept(new CallLVarsVisitor<R,A>(), arg);
      //p.bident_;
      for (basil_ir.Absyn.Expr x: p.listexpr_) {
        x.accept(new ExprVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(basil_ir.Absyn.IndirectCall p, A arg)
    { /* Code for IndirectCall goes here */
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.Assume p, A arg)
    { /* Code for Assume goes here */
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.Assert p, A arg)
    { /* Code for Assert goes here */
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
  }
  public class CallLVarsVisitor<R,A> implements basil_ir.Absyn.CallLVars.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.NoOutParams p, A arg)
    { /* Code for NoOutParams goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.LocalVars p, A arg)
    { /* Code for LocalVars goes here */
      for (basil_ir.Absyn.LVar x: p.listlvar_) {
        x.accept(new LVarVisitor<R,A>(), arg);
      }
      return null;
    }
    public R visit(basil_ir.Absyn.ListOutParams p, A arg)
    { /* Code for ListOutParams goes here */
      for (basil_ir.Absyn.LVar x: p.listlvar_) {
        x.accept(new LVarVisitor<R,A>(), arg);
      }
      return null;
    }
  }
  public class JumpVisitor<R,A> implements basil_ir.Absyn.Jump.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.GoTo p, A arg)
    { /* Code for GoTo goes here */
      for (String x: p.listbident_) {
        //x;
      }
      return null;
    }
    public R visit(basil_ir.Absyn.Unreachable p, A arg)
    { /* Code for Unreachable goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.Return p, A arg)
    { /* Code for Return goes here */
      for (basil_ir.Absyn.Expr x: p.listexpr_) {
        x.accept(new ExprVisitor<R,A>(), arg);
      }
      return null;
    }
  }
  public class LVarVisitor<R,A> implements basil_ir.Absyn.LVar.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.LVarDef p, A arg)
    { /* Code for LVarDef goes here */
      //p.bident_;
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.GlobalLVar p, A arg)
    { /* Code for GlobalLVar goes here */
      //p.bident_;
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
  }
  public class BlockVisitor<R,A> implements basil_ir.Absyn.Block.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.B p, A arg)
    { /* Code for B goes here */
      //p.bident_;
      p.addrattr_.accept(new AddrAttrVisitor<R,A>(), arg);
      //p.beginlist_;
      for (basil_ir.Absyn.Statement x: p.liststatement_) {
        x.accept(new StatementVisitor<R,A>(), arg);
      }
      p.jump_.accept(new JumpVisitor<R,A>(), arg);
      //p.endlist_;
      return null;
    }
  }
  public class PEntryVisitor<R,A> implements basil_ir.Absyn.PEntry.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.EntrySome p, A arg)
    { /* Code for EntrySome goes here */
      //p.str_;
      return null;
    }
    public R visit(basil_ir.Absyn.EntryNone p, A arg)
    { /* Code for EntryNone goes here */
      return null;
    }
  }
  public class PAddressVisitor<R,A> implements basil_ir.Absyn.PAddress.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.AddrSome p, A arg)
    { /* Code for AddrSome goes here */
      p.intval_.accept(new IntValVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.AddrNone p, A arg)
    { /* Code for AddrNone goes here */
      return null;
    }
  }
  public class InternalBlocksVisitor<R,A> implements basil_ir.Absyn.InternalBlocks.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.BSome p, A arg)
    { /* Code for BSome goes here */
      //p.beginlist_;
      for (basil_ir.Absyn.Block x: p.listblock_) {
        x.accept(new BlockVisitor<R,A>(), arg);
      }
      //p.endlist_;
      return null;
    }
    public R visit(basil_ir.Absyn.BNone p, A arg)
    { /* Code for BNone goes here */
      return null;
    }
  }
  public class ProcDefVisitor<R,A> implements basil_ir.Absyn.ProcDef.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.PD p, A arg)
    { /* Code for PD goes here */
      //p.beginrec_;
      //p.str_;
      p.paddress_.accept(new PAddressVisitor<R,A>(), arg);
      p.pentry_.accept(new PEntryVisitor<R,A>(), arg);
      p.internalblocks_.accept(new InternalBlocksVisitor<R,A>(), arg);
      //p.endrec_;
      return null;
    }
  }
  public class ParamsVisitor<R,A> implements basil_ir.Absyn.Params.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.Param p, A arg)
    { /* Code for Param goes here */
      //p.bident_;
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
  }
  public class ExprVisitor<R,A> implements basil_ir.Absyn.Expr.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.RVar p, A arg)
    { /* Code for RVar goes here */
      //p.bident_;
      p.type_.accept(new TypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.BinaryExpr p, A arg)
    { /* Code for BinaryExpr goes here */
      p.binop_.accept(new BinOpVisitor<R,A>(), arg);
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.UnaryExpr p, A arg)
    { /* Code for UnaryExpr goes here */
      p.unop_.accept(new UnOpVisitor<R,A>(), arg);
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.ZeroExtend p, A arg)
    { /* Code for ZeroExtend goes here */
      p.intval_.accept(new IntValVisitor<R,A>(), arg);
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.SignExtend p, A arg)
    { /* Code for SignExtend goes here */
      p.intval_.accept(new IntValVisitor<R,A>(), arg);
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.Extract p, A arg)
    { /* Code for Extract goes here */
      p.intval_1.accept(new IntValVisitor<R,A>(), arg);
      p.intval_2.accept(new IntValVisitor<R,A>(), arg);
      p.expr_.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.Concat p, A arg)
    { /* Code for Concat goes here */
      p.expr_1.accept(new ExprVisitor<R,A>(), arg);
      p.expr_2.accept(new ExprVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.BVLiteral p, A arg)
    { /* Code for BVLiteral goes here */
      p.intval_.accept(new IntValVisitor<R,A>(), arg);
      p.bvtype_.accept(new BVTypeVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.IntLiteral p, A arg)
    { /* Code for IntLiteral goes here */
      p.intval_.accept(new IntValVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.TrueLiteral p, A arg)
    { /* Code for TrueLiteral goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.FalseLiteral p, A arg)
    { /* Code for FalseLiteral goes here */
      return null;
    }
  }
  public class BinOpVisitor<R,A> implements basil_ir.Absyn.BinOp.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.BinOpBVBinOp p, A arg)
    { /* Code for BinOpBVBinOp goes here */
      p.bvbinop_.accept(new BVBinOpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.BinOpBVLogicalBinOp p, A arg)
    { /* Code for BinOpBVLogicalBinOp goes here */
      p.bvlogicalbinop_.accept(new BVLogicalBinOpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.BinOpBoolBinOp p, A arg)
    { /* Code for BinOpBoolBinOp goes here */
      p.boolbinop_.accept(new BoolBinOpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.BinOpIntLogicalBinOp p, A arg)
    { /* Code for BinOpIntLogicalBinOp goes here */
      p.intlogicalbinop_.accept(new IntLogicalBinOpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.BinOpIntBinOp p, A arg)
    { /* Code for BinOpIntBinOp goes here */
      p.intbinop_.accept(new IntBinOpVisitor<R,A>(), arg);
      return null;
    }
  }
  public class UnOpVisitor<R,A> implements basil_ir.Absyn.UnOp.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.UnOpBVUnOp p, A arg)
    { /* Code for UnOpBVUnOp goes here */
      p.bvunop_.accept(new BVUnOpVisitor<R,A>(), arg);
      return null;
    }
    public R visit(basil_ir.Absyn.UnOp_boolnot p, A arg)
    { /* Code for UnOp_boolnot goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.UnOp_intneg p, A arg)
    { /* Code for UnOp_intneg goes here */
      return null;
    }
  }
  public class BVUnOpVisitor<R,A> implements basil_ir.Absyn.BVUnOp.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.BVUnOp_bvnot p, A arg)
    { /* Code for BVUnOp_bvnot goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVUnOp_bvneg p, A arg)
    { /* Code for BVUnOp_bvneg goes here */
      return null;
    }
  }
  public class BVBinOpVisitor<R,A> implements basil_ir.Absyn.BVBinOp.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.BVBinOp_bvand p, A arg)
    { /* Code for BVBinOp_bvand goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvor p, A arg)
    { /* Code for BVBinOp_bvor goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvadd p, A arg)
    { /* Code for BVBinOp_bvadd goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvmul p, A arg)
    { /* Code for BVBinOp_bvmul goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvudiv p, A arg)
    { /* Code for BVBinOp_bvudiv goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvurem p, A arg)
    { /* Code for BVBinOp_bvurem goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvshl p, A arg)
    { /* Code for BVBinOp_bvshl goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvlshr p, A arg)
    { /* Code for BVBinOp_bvlshr goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvult p, A arg)
    { /* Code for BVBinOp_bvult goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvnand p, A arg)
    { /* Code for BVBinOp_bvnand goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvnor p, A arg)
    { /* Code for BVBinOp_bvnor goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvxor p, A arg)
    { /* Code for BVBinOp_bvxor goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvxnor p, A arg)
    { /* Code for BVBinOp_bvxnor goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvcomp p, A arg)
    { /* Code for BVBinOp_bvcomp goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvsub p, A arg)
    { /* Code for BVBinOp_bvsub goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvsdiv p, A arg)
    { /* Code for BVBinOp_bvsdiv goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvsrem p, A arg)
    { /* Code for BVBinOp_bvsrem goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvsmod p, A arg)
    { /* Code for BVBinOp_bvsmod goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVBinOp_bvashr p, A arg)
    { /* Code for BVBinOp_bvashr goes here */
      return null;
    }
  }
  public class BVLogicalBinOpVisitor<R,A> implements basil_ir.Absyn.BVLogicalBinOp.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvule p, A arg)
    { /* Code for BVLogicalBinOp_bvule goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvugt p, A arg)
    { /* Code for BVLogicalBinOp_bvugt goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvuge p, A arg)
    { /* Code for BVLogicalBinOp_bvuge goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvslt p, A arg)
    { /* Code for BVLogicalBinOp_bvslt goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvsle p, A arg)
    { /* Code for BVLogicalBinOp_bvsle goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvsgt p, A arg)
    { /* Code for BVLogicalBinOp_bvsgt goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvsge p, A arg)
    { /* Code for BVLogicalBinOp_bvsge goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bveq p, A arg)
    { /* Code for BVLogicalBinOp_bveq goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvneq p, A arg)
    { /* Code for BVLogicalBinOp_bvneq goes here */
      return null;
    }
  }
  public class IntBinOpVisitor<R,A> implements basil_ir.Absyn.IntBinOp.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.IntBinOp_intadd p, A arg)
    { /* Code for IntBinOp_intadd goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.IntBinOp_intmul p, A arg)
    { /* Code for IntBinOp_intmul goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.IntBinOp_intsub p, A arg)
    { /* Code for IntBinOp_intsub goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.IntBinOp_intdiv p, A arg)
    { /* Code for IntBinOp_intdiv goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.IntBinOp_intmod p, A arg)
    { /* Code for IntBinOp_intmod goes here */
      return null;
    }
  }
  public class IntLogicalBinOpVisitor<R,A> implements basil_ir.Absyn.IntLogicalBinOp.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.IntLogicalBinOp_inteq p, A arg)
    { /* Code for IntLogicalBinOp_inteq goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.IntLogicalBinOp_intneq p, A arg)
    { /* Code for IntLogicalBinOp_intneq goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.IntLogicalBinOp_intlt p, A arg)
    { /* Code for IntLogicalBinOp_intlt goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.IntLogicalBinOp_intle p, A arg)
    { /* Code for IntLogicalBinOp_intle goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.IntLogicalBinOp_intgt p, A arg)
    { /* Code for IntLogicalBinOp_intgt goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.IntLogicalBinOp_intge p, A arg)
    { /* Code for IntLogicalBinOp_intge goes here */
      return null;
    }
  }
  public class BoolBinOpVisitor<R,A> implements basil_ir.Absyn.BoolBinOp.Visitor<R,A>
  {
    public R visit(basil_ir.Absyn.BoolBinOp_booleq p, A arg)
    { /* Code for BoolBinOp_booleq goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BoolBinOp_boolneq p, A arg)
    { /* Code for BoolBinOp_boolneq goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BoolBinOp_booland p, A arg)
    { /* Code for BoolBinOp_booland goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BoolBinOp_boolor p, A arg)
    { /* Code for BoolBinOp_boolor goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BoolBinOp_boolimplies p, A arg)
    { /* Code for BoolBinOp_boolimplies goes here */
      return null;
    }
    public R visit(basil_ir.Absyn.BoolBinOp_boolequiv p, A arg)
    { /* Code for BoolBinOp_boolequiv goes here */
      return null;
    }
  }
}
