// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class AddrSome  extends PAddress {
  public final IntLit intlit_;
  public AddrSome(IntLit p1) { intlit_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.PAddress.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.AddrSome) {
      basil_ir.Absyn.AddrSome x = (basil_ir.Absyn.AddrSome)o;
      return this.intlit_.equals(x.intlit_);
    }
    return false;
  }

  public int hashCode() {
    return this.intlit_.hashCode();
  }


}
