// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class Assert  extends Statement {
  public final Expr expr_;
  public Assert(Expr p1) { expr_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.Assert) {
      basil_ir.Absyn.Assert x = (basil_ir.Absyn.Assert)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
