// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class AssignStmt  extends Statement {
  public final Assign assign_;
  public AssignStmt(Assign p1) { assign_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.AssignStmt) {
      basil_ir.Absyn.AssignStmt x = (basil_ir.Absyn.AssignStmt)o;
      return this.assign_.equals(x.assign_);
    }
    return false;
  }

  public int hashCode() {
    return this.assign_.hashCode();
  }


}
