// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public abstract class Assign implements java.io.Serializable {
  public abstract <R,A> R accept(Assign.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(basil_ir.Absyn.IntAssign p, A arg);
    public R visit(basil_ir.Absyn.BVAssign p, A arg);
    public R visit(basil_ir.Absyn.BoolAssign p, A arg);

  }

}
