// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BitvectorExpr  extends Expr {
  public final BVExpr bvexpr_;
  public BitvectorExpr(BVExpr p1) { bvexpr_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BitvectorExpr) {
      basil_ir.Absyn.BitvectorExpr x = (basil_ir.Absyn.BitvectorExpr)o;
      return this.bvexpr_.equals(x.bvexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.bvexpr_.hashCode();
  }


}
