// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BoolAssign  extends Assign {
  public final BoolLVar boollvar_;
  public final LogExpr logexpr_;
  public BoolAssign(BoolLVar p1, LogExpr p2) { boollvar_ = p1; logexpr_ = p2; }

  public <R,A> R accept(basil_ir.Absyn.Assign.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BoolAssign) {
      basil_ir.Absyn.BoolAssign x = (basil_ir.Absyn.BoolAssign)o;
      return this.boollvar_.equals(x.boollvar_) && this.logexpr_.equals(x.logexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.boollvar_.hashCode())+this.logexpr_.hashCode();
  }


}
