// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BoolLVarLocalBoolLVar  extends BoolLVar {
  public final LocalBoolLVar localboollvar_;
  public BoolLVarLocalBoolLVar(LocalBoolLVar p1) { localboollvar_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.BoolLVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BoolLVarLocalBoolLVar) {
      basil_ir.Absyn.BoolLVarLocalBoolLVar x = (basil_ir.Absyn.BoolLVarLocalBoolLVar)o;
      return this.localboollvar_.equals(x.localboollvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.localboollvar_.hashCode();
  }


}
