// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BoolBinExp  extends LogicalExpr {
  public final BoolBinOp boolbinop_;
  public final LogicalExpr logicalexpr_1, logicalexpr_2;
  public BoolBinExp(BoolBinOp p1, LogicalExpr p2, LogicalExpr p3) { boolbinop_ = p1; logicalexpr_1 = p2; logicalexpr_2 = p3; }

  public <R,A> R accept(basil_ir.Absyn.LogicalExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BoolBinExp) {
      basil_ir.Absyn.BoolBinExp x = (basil_ir.Absyn.BoolBinExp)o;
      return this.boolbinop_.equals(x.boolbinop_) && this.logicalexpr_1.equals(x.logicalexpr_1) && this.logicalexpr_2.equals(x.logicalexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.boolbinop_.hashCode())+this.logicalexpr_1.hashCode())+this.logicalexpr_2.hashCode();
  }


}
