// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public abstract class BoolBinOp implements java.io.Serializable {
  public abstract <R,A> R accept(BoolBinOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(basil_ir.Absyn.BoolBinOp_booleq p, A arg);
    public R visit(basil_ir.Absyn.BoolBinOp_boolneq p, A arg);
    public R visit(basil_ir.Absyn.BoolBinOp_booland p, A arg);
    public R visit(basil_ir.Absyn.BoolBinOp_boolor p, A arg);
    public R visit(basil_ir.Absyn.BoolBinOp_boolimplies p, A arg);
    public R visit(basil_ir.Absyn.BoolBinOp_boolequiv p, A arg);

  }

}
