// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BoolLit  extends LogExpr {
  public final BoolLiteral boolliteral_;
  public BoolLit(BoolLiteral p1) { boolliteral_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.LogExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BoolLit) {
      basil_ir.Absyn.BoolLit x = (basil_ir.Absyn.BoolLit)o;
      return this.boolliteral_.equals(x.boolliteral_);
    }
    return false;
  }

  public int hashCode() {
    return this.boolliteral_.hashCode();
  }


}
