// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BoolRVarBIdent  extends BoolRVar {
  public final String bident_;
  public BoolRVarBIdent(String p1) { bident_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.BoolRVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BoolRVarBIdent) {
      basil_ir.Absyn.BoolRVarBIdent x = (basil_ir.Absyn.BoolRVarBIdent)o;
      return this.bident_.equals(x.bident_);
    }
    return false;
  }

  public int hashCode() {
    return this.bident_.hashCode();
  }


}
