// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BSome  extends InternalBlocks {
  public final ListBlock listblock_;
  public BSome(ListBlock p1) { listblock_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.InternalBlocks.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BSome) {
      basil_ir.Absyn.BSome x = (basil_ir.Absyn.BSome)o;
      return this.listblock_.equals(x.listblock_);
    }
    return false;
  }

  public int hashCode() {
    return this.listblock_.hashCode();
  }


}
