// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BVAssign  extends Assign {
  public final BVLVar bvlvar_;
  public final BVExpr bvexpr_;
  public BVAssign(BVLVar p1, BVExpr p2) { bvlvar_ = p1; bvexpr_ = p2; }

  public <R,A> R accept(basil_ir.Absyn.Assign.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BVAssign) {
      basil_ir.Absyn.BVAssign x = (basil_ir.Absyn.BVAssign)o;
      return this.bvlvar_.equals(x.bvlvar_) && this.bvexpr_.equals(x.bvexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.bvlvar_.hashCode())+this.bvexpr_.hashCode();
  }


}
