// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BVBinary  extends BVExpr {
  public final BVBinOp bvbinop_;
  public final BVExpr bvexpr_1, bvexpr_2;
  public BVBinary(BVBinOp p1, BVExpr p2, BVExpr p3) { bvbinop_ = p1; bvexpr_1 = p2; bvexpr_2 = p3; }

  public <R,A> R accept(basil_ir.Absyn.BVExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BVBinary) {
      basil_ir.Absyn.BVBinary x = (basil_ir.Absyn.BVBinary)o;
      return this.bvbinop_.equals(x.bvbinop_) && this.bvexpr_1.equals(x.bvexpr_1) && this.bvexpr_2.equals(x.bvexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.bvbinop_.hashCode())+this.bvexpr_1.hashCode())+this.bvexpr_2.hashCode();
  }


}
