// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public abstract class BVBinOp implements java.io.Serializable {
  public abstract <R,A> R accept(BVBinOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(basil_ir.Absyn.BVBinOp_bvand p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvor p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvadd p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvmul p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvudiv p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvurem p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvshl p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvlshr p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvnand p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvnor p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvxor p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvxnor p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvcomp p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvsub p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvsdiv p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvsrem p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvsmod p, A arg);
    public R visit(basil_ir.Absyn.BVBinOp_bvashr p, A arg);

  }

}
