// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public abstract class BVExpr implements java.io.Serializable {
  public abstract <R,A> R accept(BVExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(basil_ir.Absyn.BVBinary p, A arg);
    public R visit(basil_ir.Absyn.BVUnary p, A arg);
    public R visit(basil_ir.Absyn.ZeroExtend p, A arg);
    public R visit(basil_ir.Absyn.SignExtend p, A arg);
    public R visit(basil_ir.Absyn.Extract p, A arg);
    public R visit(basil_ir.Absyn.Concat p, A arg);
    public R visit(basil_ir.Absyn.BVLiteral p, A arg);
    public R visit(basil_ir.Absyn.RBVVar p, A arg);

  }

}
