// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BVLiteral1  extends BVLiteral {
  public final Int int_;
  public final BVType bvtype_;
  public BVLiteral1(Int p1, BVType p2) { int_ = p1; bvtype_ = p2; }

  public <R,A> R accept(basil_ir.Absyn.BVLiteral.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BVLiteral1) {
      basil_ir.Absyn.BVLiteral1 x = (basil_ir.Absyn.BVLiteral1)o;
      return this.int_.equals(x.int_) && this.bvtype_.equals(x.bvtype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.int_.hashCode())+this.bvtype_.hashCode();
  }


}
