// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BVLiteralBitvectorDec  extends BVLiteral {
  public final String bitvectordec_;
  public BVLiteralBitvectorDec(String p1) { bitvectordec_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.BVLiteral.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BVLiteralBitvectorDec) {
      basil_ir.Absyn.BVLiteralBitvectorDec x = (basil_ir.Absyn.BVLiteralBitvectorDec)o;
      return this.bitvectordec_.equals(x.bitvectordec_);
    }
    return false;
  }

  public int hashCode() {
    return this.bitvectordec_.hashCode();
  }


}
