// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BVLogicalBinOp_bvsle  extends BVLogicalBinOp {
  public BVLogicalBinOp_bvsle() { }

  public <R,A> R accept(basil_ir.Absyn.BVLogicalBinOp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BVLogicalBinOp_bvsle) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
