// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public abstract class BVLogBinOp implements java.io.Serializable {
  public abstract <R,A> R accept(BVLogBinOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(basil_ir.Absyn.BVLogBinOp_bvule p, A arg);
    public R visit(basil_ir.Absyn.BVLogBinOp_bvugt p, A arg);
    public R visit(basil_ir.Absyn.BVLogBinOp_bvuge p, A arg);
    public R visit(basil_ir.Absyn.BVLogBinOp_bvslt p, A arg);
    public R visit(basil_ir.Absyn.BVLogBinOp_bvsle p, A arg);
    public R visit(basil_ir.Absyn.BVLogBinOp_bvsgt p, A arg);
    public R visit(basil_ir.Absyn.BVLogBinOp_bvsge p, A arg);
    public R visit(basil_ir.Absyn.BVLogBinOp_bveq p, A arg);
    public R visit(basil_ir.Absyn.BVLogBinOp_bvneq p, A arg);

  }

}
