// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public abstract class BVLogicalBinOp implements java.io.Serializable {
  public abstract <R,A> R accept(BVLogicalBinOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvule p, A arg);
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvugt p, A arg);
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvuge p, A arg);
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvslt p, A arg);
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvsle p, A arg);
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvsgt p, A arg);
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvsge p, A arg);
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bveq p, A arg);
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvneq p, A arg);
    public R visit(basil_ir.Absyn.BVLogicalBinOp_bvult p, A arg);

  }

}
