// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BVLVarLocalBVLVar  extends BVLVar {
  public final LocalBVLVar localbvlvar_;
  public BVLVarLocalBVLVar(LocalBVLVar p1) { localbvlvar_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.BVLVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BVLVarLocalBVLVar) {
      basil_ir.Absyn.BVLVarLocalBVLVar x = (basil_ir.Absyn.BVLVarLocalBVLVar)o;
      return this.localbvlvar_.equals(x.localbvlvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.localbvlvar_.hashCode();
  }


}
