// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BVRV  extends BVRVar {
  public final String bident_;
  public final BVType bvtype_;
  public BVRV(String p1, BVType p2) { bident_ = p1; bvtype_ = p2; }

  public <R,A> R accept(basil_ir.Absyn.BVRVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BVRV) {
      basil_ir.Absyn.BVRV x = (basil_ir.Absyn.BVRV)o;
      return this.bident_.equals(x.bident_) && this.bvtype_.equals(x.bvtype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.bident_.hashCode())+this.bvtype_.hashCode();
  }


}
