// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BVUnary  extends BVExpr {
  public final BVUnOp bvunop_;
  public final BVExpr bvexpr_;
  public BVUnary(BVUnOp p1, BVExpr p2) { bvunop_ = p1; bvexpr_ = p2; }

  public <R,A> R accept(basil_ir.Absyn.BVExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BVUnary) {
      basil_ir.Absyn.BVUnary x = (basil_ir.Absyn.BVUnary)o;
      return this.bvunop_.equals(x.bvunop_) && this.bvexpr_.equals(x.bvexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.bvunop_.hashCode())+this.bvexpr_.hashCode();
  }


}
