// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class BVUnOp_bvnot  extends BVUnOp {
  public BVUnOp_bvnot() { }

  public <R,A> R accept(basil_ir.Absyn.BVUnOp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.BVUnOp_bvnot) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
