// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class DirectCallReturn  extends Statement {
  public final ListLVar listlvar_;
  public final String bident_;
  public final ListExpr listexpr_;
  public DirectCallReturn(ListLVar p1, String p2, ListExpr p3) { listlvar_ = p1; bident_ = p2; listexpr_ = p3; }

  public <R,A> R accept(basil_ir.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.DirectCallReturn) {
      basil_ir.Absyn.DirectCallReturn x = (basil_ir.Absyn.DirectCallReturn)o;
      return this.listlvar_.equals(x.listlvar_) && this.bident_.equals(x.bident_) && this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.listlvar_.hashCode())+this.bident_.hashCode())+this.listexpr_.hashCode();
  }


}
