// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class DirectCall  extends Statement {
  public final CallLVars calllvars_;
  public final String bident_;
  public final ListExpr listexpr_;
  public DirectCall(CallLVars p1, String p2, ListExpr p3) { calllvars_ = p1; bident_ = p2; listexpr_ = p3; }

  public <R,A> R accept(basil_ir.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.DirectCall) {
      basil_ir.Absyn.DirectCall x = (basil_ir.Absyn.DirectCall)o;
      return this.calllvars_.equals(x.calllvars_) && this.bident_.equals(x.bident_) && this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.calllvars_.hashCode())+this.bident_.hashCode())+this.listexpr_.hashCode();
  }


}
