// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class EntrySome  extends PEntry {
  public final String str_;
  public EntrySome(String p1) { str_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.PEntry.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.EntrySome) {
      basil_ir.Absyn.EntrySome x = (basil_ir.Absyn.EntrySome)o;
      return this.str_.equals(x.str_);
    }
    return false;
  }

  public int hashCode() {
    return this.str_.hashCode();
  }


}
