// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class Extract  extends Expr {
  public final IntVal intval_1, intval_2;
  public final Expr expr_;
  public Extract(IntVal p1, IntVal p2, Expr p3) { intval_1 = p1; intval_2 = p2; expr_ = p3; }

  public <R,A> R accept(basil_ir.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.Extract) {
      basil_ir.Absyn.Extract x = (basil_ir.Absyn.Extract)o;
      return this.intval_1.equals(x.intval_1) && this.intval_2.equals(x.intval_2) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.intval_1.hashCode())+this.intval_2.hashCode())+this.expr_.hashCode();
  }


}
