// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class IntAssign  extends Assign {
  public final IntLVar intlvar_;
  public final IntExpr intexpr_;
  public IntAssign(IntLVar p1, IntExpr p2) { intlvar_ = p1; intexpr_ = p2; }

  public <R,A> R accept(basil_ir.Absyn.Assign.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.IntAssign) {
      basil_ir.Absyn.IntAssign x = (basil_ir.Absyn.IntAssign)o;
      return this.intlvar_.equals(x.intlvar_) && this.intexpr_.equals(x.intexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.intlvar_.hashCode())+this.intexpr_.hashCode();
  }


}
