// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public abstract class IntBinOp implements java.io.Serializable {
  public abstract <R,A> R accept(IntBinOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(basil_ir.Absyn.IntBinOp_intadd p, A arg);
    public R visit(basil_ir.Absyn.IntBinOp_intmul p, A arg);
    public R visit(basil_ir.Absyn.IntBinOp_intsub p, A arg);
    public R visit(basil_ir.Absyn.IntBinOp_intdiv p, A arg);
    public R visit(basil_ir.Absyn.IntBinOp_intmod p, A arg);

  }

}
