// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public abstract class InternalBlocks implements java.io.Serializable {
  public abstract <R,A> R accept(InternalBlocks.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(basil_ir.Absyn.BSome p, A arg);
    public R visit(basil_ir.Absyn.BNone p, A arg);

  }

}
