// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class IntegerExpr  extends Expr {
  public final IntExpr intexpr_;
  public IntegerExpr(IntExpr p1) { intexpr_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.IntegerExpr) {
      basil_ir.Absyn.IntegerExpr x = (basil_ir.Absyn.IntegerExpr)o;
      return this.intexpr_.equals(x.intexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.intexpr_.hashCode();
  }


}
