// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class IntLVarLocalIntLVar  extends IntLVar {
  public final LocalIntLVar localintlvar_;
  public IntLVarLocalIntLVar(LocalIntLVar p1) { localintlvar_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.IntLVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.IntLVarLocalIntLVar) {
      basil_ir.Absyn.IntLVarLocalIntLVar x = (basil_ir.Absyn.IntLVarLocalIntLVar)o;
      return this.localintlvar_.equals(x.localintlvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.localintlvar_.hashCode();
  }


}
