// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class IntLogBinary  extends LogExpr {
  public final IntLogicalBinOp intlogicalbinop_;
  public final IntExpr intexpr_1, intexpr_2;
  public IntLogBinary(IntLogicalBinOp p1, IntExpr p2, IntExpr p3) { intlogicalbinop_ = p1; intexpr_1 = p2; intexpr_2 = p3; }

  public <R,A> R accept(basil_ir.Absyn.LogExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.IntLogBinary) {
      basil_ir.Absyn.IntLogBinary x = (basil_ir.Absyn.IntLogBinary)o;
      return this.intlogicalbinop_.equals(x.intlogicalbinop_) && this.intexpr_1.equals(x.intexpr_1) && this.intexpr_2.equals(x.intexpr_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.intlogicalbinop_.hashCode())+this.intexpr_1.hashCode())+this.intexpr_2.hashCode();
  }


}
