// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class IntRVarBIdent  extends IntRVar {
  public final String bident_;
  public IntRVarBIdent(String p1) { bident_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.IntRVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.IntRVarBIdent) {
      basil_ir.Absyn.IntRVarBIdent x = (basil_ir.Absyn.IntRVarBIdent)o;
      return this.bident_.equals(x.bident_);
    }
    return false;
  }

  public int hashCode() {
    return this.bident_.hashCode();
  }


}
