// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class IRV  extends IntRVar {
  public final String bident_;
  public final IntType inttype_;
  public IRV(String p1, IntType p2) { bident_ = p1; inttype_ = p2; }

  public <R,A> R accept(basil_ir.Absyn.IntRVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.IRV) {
      basil_ir.Absyn.IRV x = (basil_ir.Absyn.IRV)o;
      return this.bident_.equals(x.bident_) && this.inttype_.equals(x.inttype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.bident_.hashCode())+this.inttype_.hashCode();
  }


}
