// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public abstract class Jump implements java.io.Serializable {
  public abstract <R,A> R accept(Jump.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(basil_ir.Absyn.GoTo p, A arg);
    public R visit(basil_ir.Absyn.Unreachable p, A arg);
    public R visit(basil_ir.Absyn.Return p, A arg);

  }

}
