// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class LetDecl  extends Declaration {
  public final String bident_;
  public final MExpr mexpr_;
  public LetDecl(String p1, MExpr p2) { bident_ = p1; mexpr_ = p2; }

  public <R,A> R accept(basil_ir.Absyn.Declaration.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.LetDecl) {
      basil_ir.Absyn.LetDecl x = (basil_ir.Absyn.LetDecl)o;
      return this.bident_.equals(x.bident_) && this.mexpr_.equals(x.mexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.bident_.hashCode())+this.mexpr_.hashCode();
  }


}
