// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class Local  extends LVar {
  public final String bident_;
  public final Type type_;
  public Local(String p1, Type p2) { bident_ = p1; type_ = p2; }

  public <R,A> R accept(basil_ir.Absyn.LVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.Local) {
      basil_ir.Absyn.Local x = (basil_ir.Absyn.Local)o;
      return this.bident_.equals(x.bident_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.bident_.hashCode())+this.type_.hashCode();
  }


}
