// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class LogicalExpr  extends Expr {
  public final LogExpr logexpr_;
  public LogicalExpr(LogExpr p1) { logexpr_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.LogicalExpr) {
      basil_ir.Absyn.LogicalExpr x = (basil_ir.Absyn.LogicalExpr)o;
      return this.logexpr_.equals(x.logexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.logexpr_.hashCode();
  }


}
