// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class LogicalE  extends Expr {
  public final LogicalExpr logicalexpr_;
  public LogicalE(LogicalExpr p1) { logicalexpr_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.LogicalE) {
      basil_ir.Absyn.LogicalE x = (basil_ir.Absyn.LogicalE)o;
      return this.logicalexpr_.equals(x.logicalexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.logicalexpr_.hashCode();
  }


}
