// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class LVarIntLVar  extends LVar {
  public final IntLVar intlvar_;
  public LVarIntLVar(IntLVar p1) { intlvar_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.LVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.LVarIntLVar) {
      basil_ir.Absyn.LVarIntLVar x = (basil_ir.Absyn.LVarIntLVar)o;
      return this.intlvar_.equals(x.intlvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.intlvar_.hashCode();
  }


}
