// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class LVarBVLVar  extends LVar {
  public final BVLVar bvlvar_;
  public LVarBVLVar(BVLVar p1) { bvlvar_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.LVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.LVarBVLVar) {
      basil_ir.Absyn.LVarBVLVar x = (basil_ir.Absyn.LVarBVLVar)o;
      return this.bvlvar_.equals(x.bvlvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.bvlvar_.hashCode();
  }


}
