// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class LVarBoolLVar  extends LVar {
  public final BoolLVar boollvar_;
  public LVarBoolLVar(BoolLVar p1) { boollvar_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.LVar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.LVarBoolLVar) {
      basil_ir.Absyn.LVarBoolLVar x = (basil_ir.Absyn.LVarBoolLVar)o;
      return this.boollvar_.equals(x.boollvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.boollvar_.hashCode();
  }


}
