// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public abstract class Params implements java.io.Serializable {
  public abstract <R,A> R accept(Params.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(basil_ir.Absyn.Param p, A arg);

  }

}
