// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class PD  extends ProcDef {
  public final String beginrec_, str_, endrec_;
  public final PAddress paddress_;
  public final PEntry pentry_;
  public final InternalBlocks internalblocks_;
  public PD(String p1, String p2, PAddress p3, PEntry p4, InternalBlocks p5, String p6) { beginrec_ = p1; str_ = p2; paddress_ = p3; pentry_ = p4; internalblocks_ = p5; endrec_ = p6; }

  public <R,A> R accept(basil_ir.Absyn.ProcDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.PD) {
      basil_ir.Absyn.PD x = (basil_ir.Absyn.PD)o;
      return this.beginrec_.equals(x.beginrec_) && this.str_.equals(x.str_) && this.paddress_.equals(x.paddress_) && this.pentry_.equals(x.pentry_) && this.internalblocks_.equals(x.internalblocks_) && this.endrec_.equals(x.endrec_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(37*(this.beginrec_.hashCode())+this.str_.hashCode())+this.paddress_.hashCode())+this.pentry_.hashCode())+this.internalblocks_.hashCode())+this.endrec_.hashCode();
  }


}
