// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public abstract class PExit implements java.io.Serializable {
  public abstract <R,A> R accept(PExit.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(basil_ir.Absyn.ESome p, A arg);
    public R visit(basil_ir.Absyn.ENone p, A arg);

  }

}
