// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class Procedure  extends Declaration {
  public final String bident_;
  public final ListParams listparams_1, listparams_2;
  public final ProcDef procdef_;
  public Procedure(String p1, ListParams p2, ListParams p3, ProcDef p4) { bident_ = p1; listparams_1 = p2; listparams_2 = p3; procdef_ = p4; }

  public <R,A> R accept(basil_ir.Absyn.Declaration.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.Procedure) {
      basil_ir.Absyn.Procedure x = (basil_ir.Absyn.Procedure)o;
      return this.bident_.equals(x.bident_) && this.listparams_1.equals(x.listparams_1) && this.listparams_2.equals(x.listparams_2) && this.procdef_.equals(x.procdef_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.bident_.hashCode())+this.listparams_1.hashCode())+this.listparams_2.hashCode())+this.procdef_.hashCode();
  }


}
