// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class Prog  extends Program {
  public final ListDeclaration listdeclaration_;
  public Prog(ListDeclaration p1) { listdeclaration_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.Prog) {
      basil_ir.Absyn.Prog x = (basil_ir.Absyn.Prog)o;
      return this.listdeclaration_.equals(x.listdeclaration_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdeclaration_.hashCode();
  }


}
