// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class RAnyVar  extends Expr {
  public final RVar rvar_;
  public RAnyVar(RVar p1) { rvar_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.RAnyVar) {
      basil_ir.Absyn.RAnyVar x = (basil_ir.Absyn.RAnyVar)o;
      return this.rvar_.equals(x.rvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.rvar_.hashCode();
  }


}
