// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class RBVVar  extends BVExpr {
  public final BVRVar bvrvar_;
  public RBVVar(BVRVar p1) { bvrvar_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.BVExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.RBVVar) {
      basil_ir.Absyn.RBVVar x = (basil_ir.Absyn.RBVVar)o;
      return this.bvrvar_.equals(x.bvrvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.bvrvar_.hashCode();
  }


}
