// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class RIntVar  extends IntExpr {
  public final IntRVar intrvar_;
  public RIntVar(IntRVar p1) { intrvar_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.IntExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.RIntVar) {
      basil_ir.Absyn.RIntVar x = (basil_ir.Absyn.RIntVar)o;
      return this.intrvar_.equals(x.intrvar_);
    }
    return false;
  }

  public int hashCode() {
    return this.intrvar_.hashCode();
  }


}
