// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class SAssign  extends Statement {
  public final LVar lvar_;
  public final Expr expr_;
  public SAssign(LVar p1, Expr p2) { lvar_ = p1; expr_ = p2; }

  public <R,A> R accept(basil_ir.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.SAssign) {
      basil_ir.Absyn.SAssign x = (basil_ir.Absyn.SAssign)o;
      return this.lvar_.equals(x.lvar_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.lvar_.hashCode())+this.expr_.hashCode();
  }


}
