// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class ShortBVT  extends BVType {
  public final String bvtype_;
  public ShortBVT(String p1) { bvtype_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.BVType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.ShortBVT) {
      basil_ir.Absyn.ShortBVT x = (basil_ir.Absyn.ShortBVT)o;
      return this.bvtype_.equals(x.bvtype_);
    }
    return false;
  }

  public int hashCode() {
    return this.bvtype_.hashCode();
  }


}
