// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class SignExtend  extends Expr {
  public final IntVal intval_;
  public final Expr expr_;
  public SignExtend(IntVal p1, Expr p2) { intval_ = p1; expr_ = p2; }

  public <R,A> R accept(basil_ir.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.SignExtend) {
      basil_ir.Absyn.SignExtend x = (basil_ir.Absyn.SignExtend)o;
      return this.intval_.equals(x.intval_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.intval_.hashCode())+this.expr_.hashCode();
  }


}
