// File generated by the BNF Converter (bnfc 2.9.5).

package basil_ir.Absyn;

public class TypeIntType  extends Type {
  public final IntType inttype_;
  public TypeIntType(IntType p1) { inttype_ = p1; }

  public <R,A> R accept(basil_ir.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof basil_ir.Absyn.TypeIntType) {
      basil_ir.Absyn.TypeIntType x = (basil_ir.Absyn.TypeIntType)o;
      return this.inttype_.equals(x.inttype_);
    }
    return false;
  }

  public int hashCode() {
    return this.inttype_.hashCode();
  }


}
